### ISSUE TITLE
add functionality for logging messages per channel

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifugo#102]
There should be an option to have centrifugo store all chat messages from a channel session into a log. 

Sometimes there's a need to have backup messages for verification/legal reasons. For instance, someone using my app my claim to not have receive a message from the sender in order to make a false claim for momentary gain. 

I'm know this could be implemented manually be setting up Centrifugo to direct communications to the server first before it reaches the receiver of the message, but I feel this should already be a built-in feature of Centrifugo. Also utilizing the speed of Go instead of an interpret language (ie. PHP) is another motivation behind the push for this feature.

**Comment by banks** [comment]
While this may be a reasonable feature, if be pretty wary of claiming/assuming it could help in legal disputes. 

Even if you have a log, it's no guarantee that the users client ever received the message sent nor that your app displayed it correctly and even if it did all that, still no evidence the user actually missed it while refreshing the page etc. 

This kind of audit trail really needs to be in your primary data store - I.e if you have messages that are this important then they should be stored in your primary store and marked as read by your app separately from centrifugo. 

Centrifugo is a best-effort message transport and should not be relied on as the source of truth for any data at all including a record of "what happened" in your app. 

It might be interesting to have this feature but I think it's dangerous to assume it's useful beyond debugging and certainly not as your primary audit trail of app messages sent.

**Comment by lmj0011** [comment]
>This kind of audit trail really needs to be in your primary data store

in comes Redux

**Comment by sandeep-sidhu** [comment]
not sure about legal reasons but we definitely need a feature where  you can point centrifugal to some backend database and it saves keeps room's message history.

**Comment by banks** [comment]
@sandeep-sidhu please explain why you need this. 

Even if we add this, the data really shouldn't be used for anything more than debugging or large scale aggregate analytics. We just can't provide strong enough guarantees for it to be useful for anything else and I worry that even if you know that, the presence of the feature in general will be misunderstood by others and used inappropriately.

Philosophically I dislike this because centrifugo is a best-effort message transport. Any truth about history or state should come from your app and be stored somewhere appropriate with well controlled semantics that match your requirements. Centrifugo should never be a source of truth for anything that happened. Think of it more like using Apple Push Notification Service - you wouldn't request that they add logging for your app's source of truth about messages sent, you'd do it in your app. Centrifugo should be treated with the same expectations with respect to its role in your architecture. 

It does have some state but that is only enough to ride out temporary disconnections in a "best effort" sense - just like other transport systems. It's important not to confuse that with being source of truth about what was delivered etc. 

The one thing here I see as a possibly useful thing would be logging of messages published and sent in the same way a web server logs - these could be used for analytics or debugging or security, but with the same understanding that they are not primary source of truth for your app. I'd push for doing this via some standard logging protocol like syslogd which can be consumed by almost any log aggregation tool. 

Hope this helps.

**Comment by banks** [comment]
One additional disconnect in this discussion - I'm assuming you don't use centrifugo clients to publish although that seems to be the original post's use case. I know this is a feature offered but it's one we seriously considered removing as it has all sorts of issue like this for any real application. Even for high-velocity chat apps posting new messages should really go back through your app rather than just relayed through centrifugo.

So when I say it's just a transport, I'm really implying that IMO you should be publishing from clients at all and it should be a ONE WAY push transport with all state flowing trough your app first. 

If you really need two way websockets for your app (a very small minority's of real time app's do) then it's likely centrifugo is not a good fit for exactly this reason - no clean way to hook those client-published messages back into all the normal functions of your app like persistence, analytics etc. You will likely end up building a custom staateful websocket server in that case and we shouldn't add features to centrifugo to support a use case it's not really a good answer to anyway.

**Comment by FZambia** [comment]
Sorry for late reply, in vacation currently.

As @banks said Centrifugo is just a way to quickly deliver real-time messages to connected clients. Any
additional logic should be implemented on top of your application layer. This includes message history, permission check when user generates new event, message acknowledgent logic, sending PUSH messages over APNS or CGM to users which have not acknowledged message delivery in some interval. This is design decision and I doubt it will change. The only way is #100 which can theoretically make it possible to write custom parts.

Here I see reasonable to add logging messages to TRACE log level just to make debugging easier. Any reliable and legal history handling should be in application. Possibility to use Centrifugo without backend only suitable for demos, personal usage or maybe using Centrifugo as microservice on backend (without real users from the wild connected to it).

**Comment by sandeep-sidhu** [comment]
hmmm.. okay.  First of all thanks for the responses, really appreciate the quick and details responses.

As @banks assumed I'm actually using https://github.com/centrifugal/centrifuge-js currently and publishing messages from clients.. well it started initially as poc to see if I can centrifigual to build my chat application and also the page here made no reference for me to avoid going down that route..  https://fzambia.gitbooks.io/centrifugal/content/clients/javascript.html but anyway.. I'm right now facing the problem of having no history of the chat rooms.

I was hoping the clients do the authentication with my App which issues auth tokens to user depending on if they can publish to a room or not and then everything gets offloaded to centrifugo and all connected clients can keep chatting to each other without my application doing any message handling.

But I see that this is not going to be the solution for now, so I'll look into publishing messages back to my app and.  Just additional work for me now I guess.  Anways thanks for the responses, I'll hit the gitter room in case I run into any other things.

**Comment by FZambia** [comment]
@sandeep-sidhu sorry that docs are not so clear about idiomatic Centrifugo usage. Will try to find a way to emphasize this. Centrifugo is not a chat solution - it's more general purpose - for all kinds of real-time applications (well, except very dynamic multiplayer games), so it can not provide logic specific to concrete real-time app implementation. Its initial goal was to provide a way to create real-time apps to backends which are not very suitable for this - i.e. synchronous worker-model when lots of persistent connections is a big trouble. So it gives a solution for dealing with such connections and design that allows to implement any additional logic on application backend. Which is pretty flexible in many cases and let to keep Centrifugo core small.

**Comment by FZambia** [comment]
Closing this - we are not planning to add this functionality to Centrifugo due to reasons described above. Looks like I will add TRACE logging of messages coming to node (already opened pull request with this) but it's **just for debugging** purposes - you should not rely on it. Because I can not guarantee logging format. And more important - it's not reliable anyway - we can not say exactly if user have read that message or not - handling this is a task for application.
