### ISSUE TITLE
Consider exposing prometheus metrics endpoint

### ISSUE THREAD

**Issue by oddurmagg** [centrifugal/centrifugo#104]
I would love to monitor the centrifugo deployment using prometheus : prometheus.io

Exposing metrics using the prometheus client library is quite an easy task..

**Comment by FZambia** [comment]
Hello! I think this could be nice... But it could be pretty straightforward to implement if we had no metrics yet. As we already have our own metrics collecting mechanism looks that we need a way to integrate it with prometheus. I never worked with prometheus before so need some help here.

We have metrics that we can access from handlers in any time. So we can set prometheus metrics once it requests `/metrics` endpoint? But it will be anyway code duplication - i.e. we need at least initialize counters, gauges from prometheus client library to get a chance to set them. What to do with our latencies based on hdr histograms that will appear in next release - export them as gauge values?

Maybe I am missing a better way?

**Comment by oddurmagg** [comment]
Either that or expose the already collected metrics in the format that Prometheus scrapes it in, which is a trivial text format. 

I´m gonna take a look at how metrics are collected atm in centrifugo to see how much work it would be to pipe them to the golang prometheus library.

**Comment by FZambia** [comment]
I personally prefer the option to just export current metric values into prometheus format on `/metric` endpoint - as the text format rather trivial. Duplicating instruments using prometheus client library primitives looks not elegant. Also looks like we need custom authentication for this endpoint - as far as I understand Bearer token.

**Comment by FZambia** [comment]
@oddurmagg I am in process of refactoring Centrifugo internals, this can take some time as this is quite big job, metrics will be slightly changed too I think - I suppose it will be easier to do this issue on top of those changes.

**Comment by FZambia** [comment]
I started to implement this recently and the more I think about this the more I feel that this should not be in scope of Centrifugo core functionality - this is a new HTTP endpoint with its own auth. We already provide a way to aggregate stats over time interval and raw node stats. And API to export them - `stats` (aggregated info) and `node` (per-node non-aggregated info) commands.

I see how this can simplify life for Prometheus users though. Python version of Centrifugo (Centrifuge) had a possibility to periodically export metrics into Graphite. Prometheus also has Pushgateway (https://prometheus.io/docs/instrumenting/pushing/). Maybe we should support pushing metrics instead of introducing new endpoints. On the other side having too much functionality in core for all cases does not seem like a good idea - more code to support, more dependencies. So another solution here - build a tool that can grab Centrifugo metrics and export them into desired destination.

**Comment by banks** [comment]
One thing to bear in mind Alexandr is that Prometheus' push gateway is kind of a hack. 

Prometheus' whole system model assumes that when it scrapes an endpoint it's getting metric values that are valid right now - I.e the endpoint is actually "measuring" and returning the current thing.

The push gateway subverts that. In general it can work OK in simple cases but it quickly breaks down if you have metrics which change cardinality often for example - if you replace metrics into the push gateway you can end up loosing data when the push and scrape intervals don't perfectly align which can happen a lot in practice due timing fluctuations. If you don't replace then metrics never go away and you end up scraping and storing stale and static metrics in Prometheus for systems that are long gone which is wasteful and confusing. 

I've run into all these issues recently and was part of helping to find a solution for Telegraf that properly handled these cases in as-close-as-possible way to matching a push system with Prometheus' system model. 

I'm not sure these specific issues are a big deal for Centrifugo, but you'd need to write custom code to support push gateway anyway since we don't export stats in any of the currently supported output formats IIRC. Or perhaps we do with graphite you mentioned? But graphite doesn't support histograms for timing so we'd loose all the usefulness of that data that way. (Prometheus clients support exporting histograms that can preserve that data properly). 

I see three reasonable options:

 1. Don't support Prometheus- leave users to build something with push gateway and graphite collector and figure out the gotchas and subtleties of all the different system assumptions themselves
 2. Use the Prometheus client library in Centrifugo and integrate with current metrics by implementing Prometheus' Collector interface in our metrics object. Their library will add the endpoint etc. for you and should be just a few lines of code. 
 3. Write an external "centrifugo collector" daemon for Prometheus that uses the Prometheus client and then executes a stats call to Prometheus on each scrape and returns the metrics scraped to Prometheus via the client. (This is the same as 2 except the code lives in a separate daemon and needs an RPC to centrifugo to scrape rather than reading from memory.)

I don't have a strong opinion, but considering how popular Prometheus is becoming, I'd suggest one of the second two options leaves us in a better place for adoption.

**Comment by nordicdyno** [comment]
I'm voting for option 2 (integration with Prometheus out the box). Any plans on this? Probably I can implement this feature if you help me a bit.
@FZambia

**Comment by FZambia** [comment]
@nordicdyno if this integration is so painless as @banks described as option 2 I don't see why we should not do it, but personally I didn't look at this yet - if you can investigate is it really possible it could help.

**Comment by synw** [comment]
To advocate for solution 3 the "centrifugo collector" daemon sounds nice. If it could be extendable to distribute Centrifugo stats not only to Prometheus but to other systems as well it would be great. User case: I need to monitor what happens on some specific channels and distribute this info to third-party apps. A flexible external worker would be a good fit for the job.

The approach 3 looks very interesting if it could be extendable.

**Comment by nanom1t** [comment]
Which tools can I use to monitor metrics for Centrifugo (for example, number of opened connections, requests per second, graphics and so on) on my server? Here https://fzambia.gitbooks.io/centrifugal/content/server/stats.html I've found stats API command, but it returns only JSON.

**Comment by FZambia** [comment]
@nanom1t not sure I understand your question right - you can call this `stats` API command using any of our HTTP API clients and do whatever you need with metric values - as an example you can send them to Graphite and use Grafana for displaying and alerting, or just analize received values and use any grapph display/alerting system you have.

**Comment by FZambia** [comment]
@synw I personally agree that metric collector really should be outside of Centrifugo as we can't support all metric storages out of the box. Prometheus is the only exception here I suppose as it looks like standard for instrumenting Go code at moment. So if it's possible to integrate with Prometheus without extra need to write custom HTTP Request Handler manually - we can integrate with it in the core.

**Comment by synw** [comment]
@nanom1t : the terminal client has a [stats command ](https://github.com/synw/centcli#statistics): it is useful to keep an eye on a number but not for serious monitoring

**Comment by nanom1t** [comment]
Thanks for your responses. I will try to check Graphite and Grafana.

**Comment by nordicdyno** [comment]
I've written PoC of Centrifugo exporter: https://github.com/nordicdyno/centrifugo_exporter.
Metrics subset proxied from JSON endpoint is described in code here: https://github.com/nordicdyno/centrifugo_exporter/blob/master/main.go#L61 It's easy to add others if anybody wants – PRs are appreciated.

The main problem now, current JSON endpoint exports metrics from all nodes. This is not how Prometheus exporters supposed to work. Exporters should be work for every node, for "up" checks and metrics availability. I think better solutions is to add Prometheus `/metrics` endpoint support, probably on its own port without any auth logic. Alternative is to add query parameter for current JSON metrics endpoint like `only-this-node=true` and write "official" exporter for centrifugo

**Comment by FZambia** [comment]
@nordicdyno thanks for your attention to this. Btw there is also [node](https://fzambia.gitbooks.io/centrifugal/content/server/api.html#node-centrifugo--140) API command that returns raw non-aggregated stats per node - it's not implemented in API clients because it behaves differently (other commands are node agnostic). 

But looks like it's not very comfortable to start and configure custom proxy just to ask that `node` command from every Centrifugo node and we need to support this out of the box. Maybe refactoring our internal metrics to use Prometheus primitives - not sure about this though, needs investigation.

**Comment by nordicdyno** [comment]
Thank you for pointing on `/node` method. I missed it, unfortunately. Soon I've modified my exporter with support this method. Also, I've found there is no `Node()` method in `gocent` lib like `Stat()`, so I implemented it in my own code.

**Comment by FZambia** [comment]
Implemented in Centrifugo v2!
