### ISSUE TITLE
Dynamic User Channel Handling API

### ISSUE THREAD

**Issue by derkan** [centrifugal/centrifugo#106]
Hi, 
Although we have user channels and private channels, I think we need a API for dynamic channel handling and channel security. 
- user channels is not feasible when `UUID`'s are used for userid's and if we have to define many users.
- private channels are suitable if we are running only one project over centrifigo.

What I expect from HTTP API is, ie:
```json
{
    "method": "set_channel_user",
    "params": {"channel": "admin_notifications", 
               "users": {"57d6c1c8-1f5e-46ee-8c71-2bb62de02ce0":{"publish": true},
               			 "da7bf5ab-c22c-4292-be8d-1857d434f8b3":{"publish": false}
               }
   }
}
```
Here, we add two users to a channel with different privileges. We can use same message to update privilege of a user.

And later if we do not want a user to subscribe to this channel we may send this command:
```json
{
    "method": "remove_channel_user",
    "params": {"channel": "admin_notifications", 
               "users": ["57d6c1c8-1f5e-46ee-8c71-2bb62de02ce0"]
               }
}
```
Also, to clean all existing channel configs from channels beginning with ```admin:```:(for all only```*```) This may be used when user logouted or deleted.
```json
{
    "method": "clean_channel_user",
    "params": {"channel": "admin:*", 
               "users": ["57d6c1c8-1f5e-46ee-8c71-2bb62de02ce0"]
               }
}
```
And to get a user's channels:
```json
{
    "method": "get_user_channels",
    "params": ["57d6c1c8-1f5e-46ee-8c71-2bb62de02ce0"]
}
```

We can send `set_channel_user` command when a user logins from any backend project using centrifigo. 

What do you think?

**Comment by FZambia** [comment]
Hello! Thanks for proposal, but here you describe concept different from Centrifugo. 

Centrifugo goal is to be just a server keeping persistent connections that provides a way to communicate with connected users over API - i.e. is more like a transport layer for messages. As soon as something like this added you try to put permission handling from your app to Centrifugo. This is not bad in general I think but this is another software - with **persistent store to keep such per-user settings** after restart for example. That's rather critical change as now we run without any persistence and I see a great benefit in this.

Ideas you describe can suit your use case but in general this is a shift towards making Centrifugo chat framework - it's not what I want it to be. Centrifugo does not solve permission problem - it does so because it was a design decision to let application implement permissions/storing. That was an initial idea and it works for many apps. This is also like pusher.com works - Centrifugo has lots in common with that service. From conceptual point of view Centrifugo is done. At least I believe so.

Next, I don't like an idea of running multiple projects over one Centrifugo you mentioned. Multiple project support was removed in version 1.0 - it's still possible with channel prefixes though and one shared secret key but I prefer each project using its own Centrifugo and one project does not affect other in any way.

**Comment by derkan** [comment]
Hi,
Thanks. I didn't mean to persist data. It will be done as it is done in current presence data. When user disconnects, channel users data will be also gone with presence data. 

What I want is adding users to a channel by ID when creating the channel and later able to add or remove users from that channel by API. It will be actually a presence data but, centrifugal should be filtering messages on a channel by also checking its defined users by this api proposal. By this way client will send message to a channel easily  without defining target user channels. 

For single signed(token)  microservices, there are services on different platforms which is bound to a single user login/session. For per-project centrifugal installations, web browser client should connect to all these microservice servers and developer will be developing a service for private channels for each of installation of centrifugo. But, by using this api proposal, cenrifugal will not need to connect a backend for validating a client and this will be nicer for performance.

If this proposal doesn't fit for current project goals, than there is nothing to do :-) thanks for evaluating my api proposal.

**Comment by FZambia** [comment]
This is anyway must be done with persistent layer if do this right. At moment loosing all information related to channels (presence, history) is not very critical - presence will be restored automatically after some time, history mostly needed for recover mechanism - so in general apps can tolerate it. 

Permissions you suggest require extra HTTP requests from application backend, so it's not easy to restore them when lost.

Also I think it could be rather unmanageable concept (requests from backend to Centrifugo every time user connects/disconnects?) - can result it very hard to find bugs. Various race conditions for example.

**Comment by derkan** [comment]
OK, thanks.
