### ISSUE TITLE
What to do with PRIVATE_SIGN response for Private Channels

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifugo#108]
https://fzambia.gitbooks.io/centrifugal/content/mixed/private_channels.html
https://fzambia.gitbooks.io/centrifugal/content/clients/javascript.html#connection-parameters

After reading the `private_channels` section, I wasn't quite sure what to do with the data you get back from the response: 

```js
{
    "$one": {
        "sign": "PRIVATE SIGN",
        "info": ""
    }
}
```

I assume you place the `sign` for the `token` parameter. Is this correct?
```js
var centrifuge = new Centrifuge({
    url: 'http://centrifuge.example.com/connection',
    user: 'USER ID',
    timestamp: 'UNIX TIMESTAMP',
    info: '{"first_name": "Alexandr", "last_name": "Emelin"}',
    token: 'TOKEN'
});
```

**Comment by FZambia** [comment]
No, `centrifuge-js` handles that private channel sign response automatically. In connection parameters you only provide connection token for user - i.e. nothing related to private channel.

Here what happens:
* you write js code with private channel subscription `centrifuge.subscribe("$one", ...)`
* `centrifuge-js` understands that you want to subscribe on private channel because it starts with `$` symbol.
* before sending subscription request to Centrifugo `centrifuge-js` sends AJAX request to your custom application auth endpoint which returns that data you showed above.
* `centrifuge-js` after receiving response automatically add that sign into subscription request to Centrifugo.

**Comment by lmj0011** [comment]
Alright, This should be good enough for me to go off of.
