### ISSUE TITLE
Question: publish message save shared or duplicated when broadcast to many channels ?

### ISSUE THREAD

**Issue by roytan883** [centrifugal/centrifugo#124]
Hi, I just found this project recently. This project looks awesome. I'm planing change my nodjs websocket server to centrifugo for PUSH gateway (**_nodejs process will crash when memory around 1.4 GB, maybe there is some memory leak, but it is very hard to investigate_**)

Based on my experience, the way how to store publish message is critical. The memory usage is 10x or 100x.  But after i read centrifugo documentation, I can't find chapter about the storage issue. So I create this issue, hope you can clarify to make it clearer.

**In this scenario:** 
```
{
    "method": "broadcast",
    "params": {
        "channels": ["CHANNEL_1", "CHANNEL_2", "CHANNEL_3"],
        "data": {
            "input": {...size about 4KB ...}
        }
    }
}
```
So centrifugo will use 4KB or 12KB memory to save the input message?

**For real scenario:**
If I need broadcast an announcement to many channels (10K channels). 
Those channels have different setting: some of them are public, some are private, some have different  **history_size** and **history_lifetime**, some are **history_drop_inactive**.
If the message is saved by shared reference in each channel, the memory cost is cheap. But if the message is saved isolated to each channel, then it may use GB memory for just one announcement.

It is **important** factor for my current project if i change to use centrifugo, because i need channels to support organization with **tree** like structure. I need push announcement from top to bottom of the organization tree.

**Comment by banks** [comment]
Now it would indeed copy the message 10k times (or however many channels have storage enabled and/or active clients.

That said, centrifugo is not really designed for sending large messages. If your messages are more than a few hundred bytes things you should consider a different architecture. 

Most push systems like Apple APNS and GCM have the same design and suggest you push the bare minimum data needed to show that there is something new to a slider and then only pull down the detail in the client probably only if the user taps/clicks the simple notification for more. 

In this case the design of storing a reference to a message and separate message (with reference counting) adds a lot of code complexity and possibly performance loss for not so much gain. 

If you have small messages and still measure significant inefficiencies in memory due to the copying, could you paste some numbers you see? It could be nice to enable reference as an option but it's a lot of work and might be detrimental to the more common case so unless it's requested a lot and shown to be a significant cost saving I'm not convinced it's worth it. 

Usually careful design can allow small messages as well as always using history_drop_inactive (i.e. not using centrifugo as a general message store but doing that in your app DB).

**Comment by banks** [comment]
You can also for cases like this rearchitect so that everyone subscribes to a public "general announcements" channel as well as anything else your app needs and the just publish announcements to that one. 

I'd still recommend messages are minimal though - just enough info to display a notification to user and/or allow you app to go fetch the full content via your regular API if needed.

**Comment by FZambia** [comment]
Using one channel for announcements (or maybe several channels based on different user permissions) could help - if it's possible in your case of course. Also you can tune history_size and history_lifetime to reasonable values as history in Centrifugo exist mostly for recovery mechanism after short network disconnections - if you need large history then it's better to just use your main app database.

If you have 100k users online and broadcast to separate channel then announcement will take about 400mb of memory. With single channel extra memory usage for history will be about 4kb. So in general we already have mechanism to save announcements shared - shared channel.

**Comment by roytan883** [comment]
We have 110K organization now, 5 million users (onlines are few based on total users, but we still need guarantee when user online they can get missed messages from its organization). And actually in our nodejs server, we save message in shared reference way to reduce memory usage.

each organization have different users 10 ~ 5000. The biggest root organization has children about 70K sub-organization struct in **tree**.

For the bottom organization , it may has about 1~20 upper organization parents. Each parent organization can publish announcements. Parent  may only publish to its own layer, or self and direct children organization layer , or include all children organization layer. 

That means there are two options to design the push rule:

1: As your suggestion, children organization users subscribe all parents organization  channel. That will quickly increase channel users. The root organization  channel may have 3 million  users need subscribe . And the second layer organization  channel may have 2.99 million  users need subscribe. But the message only need push to one channel once. The message memory is small ,but maybe the channel will have pressure with such huge users subscription.

2: Broadcast the message to those channels which need to be notified. This means each organization  channel only have its own user subscription, but need publish the message to many channels. 

Seem both options  are not good ......

4KB just a sample to question the issue. In fact, most our message is less than 1KB. But still it is a big problem to save those message which need send down to child organization.

In our old nodejs server, all real message save in a big hash map with max TTL, each channel or topic only store the message IDs, only when push to client or client request the message, than get its real body from the message map.

For centrifugo , maybe we can do the save thing. First analyze the longest TTL time of "channels": ["CHANNEL_1", "CHANNEL_2", "CHANNEL_3"] when broadcast. Then save real message body in one big hash TTL map. Each channel only save the hash message id.

**Comment by banks** [comment]
Thanks for the info! This sounds like an interesting use-case which I've not had time to think deeply about but some immediate remarks:

 1. In theory having 5million users all subscribed to one channel is no more expensive/unscalable than having the same number of subscriptions spread across tens of thousands of channels. It's much more efficient in terms of history storage. In practice I've not tried it so you may hit new and interesting bottlenecks which we can tackle. 

 2. Supposing you do hot some limit with a single global channel, you could potentially shard it and have N channels and have each user subscribe to one based on hash of their user ID. Now you can trade off N copies of message cost against how many users per channel before you see issues. 

 3. "we still need guarantee when user online they can get missed messages from its organization" this is not a guarantee centrifugo can provide. It's strictly a "best effort" transport mechanism designed (for example) to deliver updates that occurred since a web page was loaded. It's an anti-pattern and strongly discouraged to use the history feature as a source of truth or even for "reliable delivery" where users might be disconnected for more than a few minutes at a time. If you need that it really needs to be built into your app with your app's DB as the source of truth for catching up on stuff missed while offline.

I don't think message references and deduplication is a terrible idea, but it's an optimisation for a use-case that is really outside of the core design goals IMO. 

Hope this helps.

**Comment by roytan883** [comment]
I rethink this problem today. I guess the "TREE" structure organizations should not put in centrifugo. And also the announcement should not send down in the "TREE" structure. 

Because the upper and lower organizations can remove the relation, save announcement  in each organizations is not a good idea. If the relation changed, or announcement  itself was modified, then need sync many organization's  announcement, it is lots of work.

I should only use centrifugo for real-time chat message PUSH of One2One and organization itself. 

Other group multi-layer sending messages should use QUERY sync mechanism, because most of those kinds of messages no need real-time.

**Comment by roytan883** [comment]
Today i read the source code. I think it already use message reference. 
```
byteMessage, err := resp.Marshal()
n.clients.Broadcast(ch, byteMessage)
...
func (h *clientHub) Broadcast(ch string, message []byte) error {
...
        msg := NewQueuedMessage(message, true)

	for uid := range channelSubscriptions {
		c, ok := h.conns[uid]
		if !ok {
			continue
		}
		c.Send(msg)
	}
```
It use slice []byte for QueuedMessage's Payload. So no matter how many queue used, the payload use the same slice []byte.

@banks @FZambia 
> "Now it would indeed copy the message 10k times" 

Seems it is not using deep copy depend on those source code.

**Comment by roytan883** [comment]
Seems it is not using deep copy depend on those source code ?

**Comment by roytan883** [comment]
I guess i'm wrong. 
It use message payload reference for clients, but create different new messages for channels.
At channels level, it use deep copy.


`
for i, ch := range channels {

		if string(ch) == "" {
			resp.SetErr(proto.ResponseError{proto.ErrInvalidMessage, proto.ErrorAdviceFix})
			return resp, nil
		}

		chOpts, err := n.ChannelOpts(ch)
		if err != nil {
			resp.SetErr(proto.ResponseError{err, proto.ErrorAdviceFix})
			return resp, nil
		}

		message := proto.NewMessage(ch, data, client, nil)
		if chOpts.Watch {
			byteMessage, err := json.Marshal(message)
			if err != nil {
				logger.ERROR.Println(err)
			} else {
				n.PublishAdmin(proto.NewAdminMessage("message", byteMessage))
			}
		}

		errs[i] = n.Publish(message, &chOpts)
	}
`
