### ISSUE TITLE
Additional metrics

### ISSUE THREAD

**Issue by ramon-ga** [centrifugal/centrifugo#146]
It's possible to implements some additional metrics?

- `node_uptime_sec` - Using for monitoring the uptime, if it less than 5/10mins alerting (To get informed if the server is restarted)
  - i know hat the field `started_at` exists, but i would be easier for the monitoring with an uptime field
- `node_channels: {}` - Monitoring ex. channel client count

Maybe like this:
```
"metrics": {
...
    node_uptime_sec: 1000,
    node_channels: {
        {channel_name}: {
            num_unique_clients: ,
            num_clients: 
        }
    }
...
}

OR

"metrics": {
...
    node_uptime_sec: 1000,
    channel_num_unique_clients_{channel_name}: 1000,
    channel_num_clients_{channel_name}: 1000,
...
}

```

**Comment by FZambia** [comment]
For uptime seconds it makes sense. Regarding detailed channel information - there could be tons of channels actually, maybe in your case you have tens of them, but some have thousands, another reason agains is that channel is a dynamic ephemeral thing that could be created on the fly. Due to these reasons we can't add this type of info to metrics.

**Comment by ramon-ga** [comment]
I'm happy with the uptime field. 
I didn't keep this in mind, you're right! In our case i would be not a problem, and i can get this information out by the presence command.
