### ISSUE TITLE
web admin stats seems strange

### ISSUE THREAD

**Issue by roytan883** [centrifugal/centrifugo#171]
I run the throughput.go in centrifugo examples.
```
2017/04/12 12:44:44 Total clients 100
2017/04/12 12:44:44 Total messages 50000
2017/04/12 12:44:44 msgReceived 50000
2017/04/12 12:44:44 Elapsed 774.19ms
2017/04/12 12:44:44 Msg/sec 64599
```
client looks good. But on the web admin, it says:
```
DESKTOP-7VCEQG3_8000	0	0	0	500	57693	56577	23.5 MB	0%
```
then after a while, like 30s, it change to:
```
Node name	Channels	Clients	Unique	Published	Queued	Sent	Mem	CPU
DESKTOP-7VCEQG3_8000	0	0	0	0	0	0	23.5 MB	0%
```

Two questions:
1, why the web stats is not: 500, 50000, 50000 ?
2, is the stats will be clean interval ? also i use the stats command in actions, it return 
```
"client_num_connect": 0,
"client_num_msg_published": 0,
"client_num_msg_queued": 0,
"client_num_msg_sent": 0,
"client_num_subscribe": 0,
```

**Comment by FZambia** [comment]
Hi! `stats` command returns an a aggregation over minute. During minute `stats` metrics have the same values.

> why the web stats is not: 500, 50000, 50000 ?

Because queued and sent include other type of messages - connect response, subscribe response etc

>  is the stats will be clean interval ?

Yep, every minute counters start from zero. There is `node` command that returns raw metrics from a node - web interface does not have it because it returns only current raw stats on concrete node and can't be used from web interface. 

You can try `node` command from console, first start Centrifugo in `--insecure_api` mode:

```
./centrifugo --insecure_api
```

Then

```
curl -s -X POST -H "Content-Type: application/json" -d "[{\"method\":\"node\",\"params\":{}}]" localhost:8000/api/
```

**Comment by roytan883** [comment]
Thanks, I got it
