### ISSUE TITLE
Can you set an expiration date for each message?

### ISSUE THREAD

**Issue by libsgh** [centrifugal/centrifugo#175]
If I want to accurately control the expiration time of each message, rather than through the configuration file, you can achieve it?

**Comment by FZambia** [comment]
@libsgh hello, it’s not possible:) actually I never met this requirement before, what is your use case? I suspect that if you need this then you maybe trying to use Centrifugo for a wrong task.

**Comment by libsgh** [comment]
@FZambia When a client connects the client first, from history to find news, in order to receive offline messages, but these messages are the expiration time, but can not control the expiration time of each message, the message is stored in the redis, can not be achieved by way of TTL?

**Comment by FZambia** [comment]
I can't help you much because you have not provided enough details for me to understand your use case. You should rely on your backend to recover missed (offline) messages when client opens a page/app first time. Centrifugo keeps a history in channel for at most `history_lifetime` period set in namespace config - this lifetime is only for preventing memory leaks when you have tons of channels (as we keep them in memory or Redis process memory) - so you should choose a reasonable time that suits your app. There is no way to set TTL per message and I still don't understand why you need this.

**Comment by FZambia** [comment]
@libsgh please reopen in case of new info or question
