### ISSUE TITLE
subscribe raw json message using redis channel

### ISSUE THREAD

**Issue by msaranas** [centrifugal/centrifugo#180]
My requirement is  centrifugo ios / android client is need to receive raw json message from redis channel pub sub which is published by c# client to redis.
Current implementation doesn't support custom json message because message should be marshalled using proto. How to achieve this requirment?

**Comment by FZambia** [comment]
@msaranas if I understood you right you can do this by serializing message into protobuf using our protobuf schema. But doing so you are hacking into Centrifugo internals - where no backwards compatibility guarantees exist. This way you also lose some channel related Centrifugo features. 

Do you have control over c# application? What about sending directly to Centrifugo from it using native Centrifugo API?

You can also create simple proxy to listen to Redis PUB/SUB and redirect received messages to Centrifugo API.

**Comment by msaranas** [comment]
C# connect redis and publish messages in to channels, no control, Able to receive message but error occured invalid wire type because of json protobuf marshal unmarshal.,solution need on pubsub handle message override unmarshall.
In alternative Is there any client for centrifugo in c#?

**Comment by FZambia** [comment]
You said that you have no control over c# app - why do you need client implementation then?

**Comment by msaranas** [comment]
I can propose that C# team to take and use centrifugo client instead direct redis publish

**Comment by FZambia** [comment]
Got it, you have 2 options:

1) Implement C# API client (we have no one yet) - this is not difficult, it's just properly made HTTP POST request with sign - you can look at existing clients to figure out, also [it's described in docs](https://fzambia.gitbooks.io/centrifugal/content/server/api.html). And you can disable sign check using `--insecure_api` Centrifugo flag (also [described in docs](https://fzambia.gitbooks.io/centrifugal/content/mixed/insecure_modes.html)).
2) Use Redis client but instead of PUBLISH use RPUSH command and run Centrifugo with Redis engine and `--redis_api` flag so you can RPUSH messages into Redis queue - [description in docs](https://fzambia.gitbooks.io/centrifugal/content/server/engines.html#redis-engine).
