### ISSUE TITLE
Invalid JSON formed in some messages

### ISSUE THREAD

**Issue by hudbrog** [centrifugal/centrifugo#214]
It seems that sometimes cetrifugo forms invalid json because of invalid default_info check. 
For example:
`{"method":"leave","body":{"channel":"$player:message:private:3ed9d74aeb6d5a86c04120e699304ac3","data":{"default_info":,"user":"2","client":"b841b73d-c4c8-4baf-93d8-4bf37f8cd3cc"}}}`
`{"method":"leave","body":{"channel":"$player:message:private:3ed9d74aeb6d5a86c04120e699304ac3","data":{"default_info":,"user":"2","client":"36de47fb-d543-4ba3-b274-587e167baf87"}}}`
And so on. 
In libcentrifugo/proto/response.go:25 DefaultInfo is checked for nil, but it would seem that it's sometimes set as an empty string.

**Comment by hudbrog** [comment]
Yes, we are using refresh. Even more, it would seems that most of the errors are from users who has left the page(and ws connection) open for quite some time.

**Comment by hudbrog** [comment]
Got to say - it's not a seldom occasion too. I have tens of thousands of these errors in the last couple of weeks.

**Comment by FZambia** [comment]
Yeah, so looks like it's happening because of missed info length check in refresh handler, compare: [this](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/conns/clientconn/conn.go#L589) vs [this](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/conns/clientconn/conn.go#L656). Will try to fix it today.

**Comment by FZambia** [comment]
released [1.7.9](https://github.com/centrifugal/centrifugo/releases/tag/v1.7.9) with fix - please check it out.

**Comment by hudbrog** [comment]
Thanks, been running it for 24h now, seems to be ok!
