### ISSUE TITLE
[feature] Publishing metrics to AWS Cloudwatch

### ISSUE THREAD

**Issue by vitoordaz** [centrifugal/centrifugo#246]
I've noticed that the new version of Centrifugo supports Graphite and Prometheus for publishing metrics.

What do you think about adding support for Cloudwatch as well?

I think that most Centrifugo users run it in AWS. Before there was a stats endpoint but in the new version it's no longer available.

What do you think about recovering that endpoint? This will make integration with another metrics system easier.

PS: Now I'm parsing Prometheus metrics to publish them to Cloudwatch.

**Comment by FZambia** [comment]
It was pretty handy with stats before. That allowed to better understand what's going on even without configuring integration with monitoring system (not everyone does this). And it allowed to see more information in admin web interface which is also cool.

Stats mechanism requires synchronization of stats between all running nodes so it's possible to ask full stats from any node. It worked before - so should work now too.

I am OK to get stats back but not sure how to implement this with Prometheus at moment (before we used custom metrics implementation which was simple to serialize into `map[string]int`, now we need to serialize Prometheus stats into similar `map[string]float64` I suppose). Maybe something like we do in [graphite case](https://github.com/centrifugal/centrifugo/blob/master/internal/graphite/graphite.go) should move to Centrifuge library and Graphite exporting in Centrifugo should use library method to extract current stats and send them to graphite.

**Comment by FZambia** [comment]
I came up with sth like this in order to convert Prometheus metrics to some generic form that can be used to export automatically to external system from Centrifugo and for admin web interface stats:
```
{
    "metrics": {
        "centrifuge_client_command_duration_seconds": {
            "method.connect.count.delta": 3,
            "method.connect.count.raw": 30,
            "method.connect.quantile.50": 0.000092533,
            "method.connect.quantile.90": 0.000138654,
            "method.connect.quantile.99": 0.000313045,
            "method.connect.sum.delta": 0.00034440999999999986,
            "method.connect.sum.raw": 0.0033648199999999997,
            "method.ping.count.delta": 2,
            "method.ping.count.raw": 14,
            "method.ping.quantile.50": 0.000013244,
            "method.ping.quantile.90": 0.000019972,
            "method.ping.quantile.99": 0.000036619,
            "method.ping.sum.delta": 0.00002931300000000005,
            "method.ping.sum.raw": 0.0003692980000000001
        },
        "centrifuge_node_action_count": {
            "action.add_client.delta": 3,
            "action.add_client.raw": 30,
            "action.remove_client.delta": 3,
            "action.remove_client.raw": 29
        },
        "centrifuge_node_build": {
            "version._": 1
        },
        "centrifuge_node_messages_received_count": {
            "type.control.delta": 20,
            "type.control.raw": 467,
            "type.join.delta": 3,
            "type.join.raw": 30,
            "type.leave.delta": 3,
            "type.leave.raw": 29
        },
        "centrifuge_node_messages_sent_count": {
            "type.control.delta": 20,
            "type.control.raw": 467,
            "type.join.delta": 3,
            "type.join.raw": 30,
            "type.leave.delta": 3,
            "type.leave.raw": 29
        },
        "centrifuge_node_num_channels": {
            "": 1
        },
        "centrifuge_node_num_clients": {
            "": 1
        },
        "centrifuge_node_num_users": {
            "": 1
        }
}
```

Metrics contain raw values for counters and delta values aggregated inside Go process over configured interval. It's pretty hard to do in generic way because of labels (more labels in Prometheus metric will result in new final metric path), different separators in metric paths in different metric systems. 

This information will be available at any node as method cal. Also it's possible to share this information between Centrifugo nodes to show deltas in admin interface.

I am not very happy with this result at moment... Format seems pretty odd. But this is sth that we can work with.

Currently we use code taken from Grafana to export Prometheus metrics to Graphite. It has some magic converting namespaces to Graphite paths that I'd like to avoid if we refactor that part. Approach above will result in backwards incompatible paths in Graphite. But I suppose it's an acceptable change.

@vitoordaz so if it will be possible to extract Prometheus stats in a form above we will be able to implement exporter to Clowdwatch from Centrifugo directly. But I can't estimate is the format of metrics above will allow us to export to Clowdwatch in a nice manner? Need your help with this.

Maybe it's not very clear what I am planning to do here - I can explain more, just ask me.

**Comment by FZambia** [comment]
Fixed format a bit to be more generic: https://gist.github.com/FZambia/3584bd5ca70254fe4981dcd064489409

**Comment by sj26** [comment]
This would be ace! Although I'd like to be playing with prometheus, we're still using cloudwatch and datadog.

> Stats mechanism requires synchronization of stats between all running nodes so it's possible to ask full stats from any node. It worked before - so should work now too.

Not neccessarily — as long as the hostname or something was included in a dimension then cloudwatch will aggregate them correctly if each node self-reports.

**Comment by FZambia** [comment]
> Not neccessarily — as long as the hostname or something was included in a dimension then cloudwatch will aggregate them correctly if each node self-reports.

I've meant a case when we ask for metrics in admin interface which was possible in Centrifugo v1, in this case request goes to one random Centrifugo node after load balancer so that node should know current metrics from all running nodes to properly answer. That was pretty useful to have. Currently almost finished this in [this pull request](https://github.com/centrifugal/centrifuge/pull/29).

For export to Cloudwatch we don't need this sort of sync  - right.

**Comment by FZambia** [comment]
Starting from v2.1.0 it's not too hard to implement export to Clowdwatch - just like [we already do in Graphite case](https://github.com/centrifugal/centrifugo/blob/master/internal/metrics/graphite/graphite.go) - but I need help with this, I am not a Clowdwatch user so can miss some specific things while implementing. Also don't have possibility to test it out. I think go-kit repo [has a good example](https://github.com/go-kit/kit/blob/master/metrics/cloudwatch2/cloudwatch2.go) of how to export to Clowdwatch in general.

**Comment by ilya-korotya** [comment]
@FZambia is this issues still relevant? I would like to try to add `AWS cloudwatch` to the project.

**Comment by FZambia** [comment]
@ilya-korotya hello, yes this is still actual I suppose, are you personally using Centrifugo on AWS?

**Comment by ilya-korotya** [comment]
@FZambia no, I didn't use Centrifugo on AWS. But I will try to figure it out.

**Comment by FZambia** [comment]
Closing - looks like no real interest to this as time goes.
