### ISSUE TITLE
Document GRPC API

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#258]
Starting from Centrifugo v2 we have GRPC API but it's not currently documented. Need to fix this.

**Comment by gedw99** [comment]
https://github.com/centrifugal/centrifugo/tree/nats_broker/internal/api

Looks very nice.

So this wraps everything.

I noticed NATS is not using NATS streaming. I guess this makes sense because the durability is coming from redis ? 

If you can make a simple readme to describe the use of grpc and NATS it would be great. I can try it out 

It does sound useful I must say.

**Comment by FZambia** [comment]
Yeah, I'll try to add docs on this very soon. In general this is just as simple as taking [proto file](https://github.com/centrifugal/centrifugo/blob/master/misc/proto/api.proto), generate GRPC code for any language and start using it. I don't have plans to create wrappers for various languages that have generated code based on that file and expose API on top of it as I believe it's pretty simple to just use generated code if someone interested while adding GRPC API wrappers for every language is quite a huge work.

BTW hope you noticed that GRPC API reflects server API only - https://centrifugal.github.io/centrifugo/server/api/ - i.e. it does not have any `subscribe` features to stream publications to subscribers - this is a task for our client libraries. While developing Centrifugo v2 a did several measurements showed that Websocket is better for streaming purposes of Centrifugo and I removed GRPC support for client-server communication at some point.

**Comment by FZambia** [comment]
Docs about GRPC API now available at https://centrifugal.github.io/centrifugo/server/grpc_api/
