### ISSUE TITLE
[question] Backend only subscription to channels

### ISSUE THREAD

**Issue by telemmaite** [centrifugal/centrifugo#324]
**Is it possible only the backend App to subscribe users to channels**?
Based on point 5 from here:
> 5) After connecting to **Centrifugo subscribe clients to channels they are interested in**. See more about channels in special chapter. All client libraries provide a way to handle messages coming to client from channel after subscribing to it.

I get the concept of private channels and generating/signing private channel subscription tokens. 
However, instead of doing this loop, would it be possible to forbid any user subscription to channels and allow only the backend App to do any channel subscription on behalf of the user?

---
Example would be a user joining a chat room. Currently, I get the way it works is:
1. User makes a request to the backend to join a Room A,
2. Backend checks user authorization
3. If user is allowed backend will send back a private channel subscription token with a claim allowing to join Room A.
4. The user/client uses the private channel subscription token to join the room.

This works great when the user incremental actions are the driving force on which rooms he will join.
However what if a user enters a system/app where he should be authorized to join 40+ rooms (which belong to his company/department).

Should I issue multiple tokens in this **bulk** scenario?
Would it be possible for the backend app to call centrifugo API and do this action without any loops?

**Comment by telemmaite** [comment]
One more short question.
I see that there is API endpoint `unsubscribe` which takes.
```json
{
    "method": "unsubscribe",
    "params": {
        "channel": "CHANNEL NAME",
        "user": "USER ID"
    }
}
```
But I don`t endpoint for **backend only subscription**.

**Is that possible or the only way  is client-side and following this example** -> 
https://github.com/centrifugal/examples/blob/master/tornado_application/code.html#L154

**Comment by FZambia** [comment]
Hello! There are many things to say regarding to your question.

There is no support for backend only subscriptions at moment.

First of all consider an option to use one channel instead of 40 channels. This personal channel belongs to user and you can send notifications to all users in a department known by your backend. This does not scale very well to many members in department but can be a viable option in some business scenarios. Centrifugo has broadcast API method that works pretty fast.

At moment centrifuge-js has batching logic so instead of 40 requests for private tokens you will usually  receive only one on app backend. But again - 40 channels per client does not look as good idea in general even without extra loop to get private tokens. This makes your client more complex as it should know about all departments current user belongs too and must dynamically subscribe to new ones.

Currently all API is built around the fact that client initiates subscription, so it has callback function to process messages. This is how PUB/SUB usually works everywhere. Also this allows history recovery feature to work as subscription objects on client side keep current client position in channel stream - sequence number.

Look at [pull request](https://github.com/centrifugal/centrifugo/pull/284) about possibility to proxy calls to application backend over HTTP. Theoretically we can extend that in future and add subscribe endpoint directive so Centrifugo will ask your backend for subscribe permission instead of doing this over client side private token request. But - I dont think it will solve a case where each client subscribed to many different channels at once as it will drastically increase amount of requests to app backend in non-linear way.

**Comment by telemmaite** [comment]
Hello, thanks a lot for your suggestions!

> First of all consider an option to use one channel instead of 40 channels. This personal channel belongs to user and you can send notifications to all users in a department known by your backend. This does not scale very well to many members in department but can be a viable option in some business scenarios. Centrifugo has broadcast API method that works pretty fast.

Thank you I will consider this option.

> At moment centrifuge-js has batching logic so instead of 40 requests for private tokens you will usually receive only one on app backend. But again - 40 channels per client does not look as good idea in general even without extra loop to get private tokens. This makes your client more complex as it should know about all departments current user belongs too and must dynamically subscribe to new ones.

My use case is that a user always belongs to a given private company and there should no cross-company sniffing possibility, which turns all my non-user-target channels to at least private for a given company. My backend will have to always provide private channel subscription tokens for all channels.
Backend knows about departments, and users in a way namespaced under a given company so all subscriptions are essentially backend driven and require private channel sub tokens.

>Currently all API is built around the fact that client initiates subscription, so it has callback function to process messages. This is how PUB/SUB usually works everywhere. Also this allows history recovery feature to work as subscription objects on client side keep current client position in channel stream - sequence number.

I don`t think backend subscription will break that pattern, in fact as there is backend unsubscribe functionality, it felt strange to me that I could not find the opposite.

> Look at pull request about possibility to proxy calls to application backend over HTTP. Theoretically we can extend that in future and add subscribe endpoint directive so Centrifugo will ask your backend for subscribe permission instead of doing this over client side private token request. But - I dont think it will solve a case where each client subscribed to many different channels at once as it will drastically increase amount of requests to app backend in non-linear way.

Seems pretty nice! Currently, there is no way to restrict a user from making malicious 4000 subs to a channel right?

At least it would be great to have an option to forbid any non-private client subs, for a sub to happen the backend at least should have sent a valid token.

**Comment by FZambia** [comment]
> there is no way to restrict a user from making malicious 4000 subs to a random public channels right

There are some options: `client_channel_limit` (128 default), `client_user_connection_limit`, `channel_max_length` that aim to protect from some malicious scenarios but of course not from all of them. Protection from DDOS is sth that is out of scope of this project.

> I don`t think backend subscription will break that pattern, in fact as there is backend unsubscribe functionality, it felt strange to me that I could not find the opposite.

Unsubscribe allows to disable access to channel for user immediately. If user tries to subscribe again it won't receive private token from your backend during subscription process.

**Comment by telemmaite** [comment]
Thank you @FZambia I have enough to get started!
