### ISSUE TITLE
Listen for join/leave server wide

### ISSUE THREAD

**Issue by adamcollier1** [centrifugal/centrifugo#358]
Currently I have a backend client which connects to centrifugo and listens for join/leave events to update a database..

1) is it possible to listen server wide? or wildcard channels.. for example $private/*, so every user has a $private/ channel I can listen to all at once..

2) Or is there a better way to manage join/leave server wide? I would like to know on my backend, when a user joins a certain channel and then when they leave..

Thank you.

**Comment by FZambia** [comment]
1) There is no mechanism to listen channels beyond what clients can do. Wildcard subscriptions not supported (and I doubt they will). Since in idiomatic case your clients publish events to channels through your backend you have all messages.

2) Solution depends on problem you have. Centrifugo has join/leave for client protocol, presence information in client and server API, server-side subscriptions, connect proxy. Join/leave events do not scale very well because those are instant and uncontrollable since produced by your client reconnects. I don't think relying on them is a good idea for backend task overall. Maybe you should think about alternative way. Also see https://centrifugal.github.io/centrifugo/faq/#presence-for-chat-apps-online-status-of-your-contacts - this is an answer on similar problem. I mean maybe you need separate microservice that solves your problem with some time approximation.

**Comment by adamcollier1** [comment]
Thanks for your response.

I am looking to get notification to my backend asap when a user leaves their private channel / disconnects. I understand I could poll presence from the server API, however ideally looking to not poll, and subscribe to presence. Only way I could work out how to do that was using join/leave and on my backend signing in using the client library and then monitoring join/leave.

To do this, when they subscribe to their private channel $private/* I also subscribe them automatically to $private and then monitor join/leave in $private only, assuming at the same time they are connected/disconnected from $private/*

My app is designed around them being online on the private channel

**Comment by FZambia** [comment]
At moment I can't suggest anything beyond my first comment here. Solution when single client listens to all join and leave events does not scale well and your consumer will be overwhelmed very soon. It's error-prone too since you can not reliably receive all join and leave events - some of them will be lost anyway.

**Comment by adamcollier1** [comment]
Understood, appreciate your feedback. Something to consider for the future maybe. Being able to listen to presence and not just poll the API.

**Comment by FZambia** [comment]
I don't have ideas on how to reliably solve this in a way you were asking, as I said this should be solved on another level in general or with some alternative approach. Maybe in you case losing some events is acceptable - without full understanding of problem context I can not do a lot. Feel free to discuss possible ideas in our Telegram chat, don't think this should be open as at this moment it's not actionable.
