### ISSUE TITLE
[question] "channels" call via cluster

### ISSUE THREAD

**Issue by sh3244** [centrifugal/centrifugo#382]
**Ask your question**
> Please provide as many details as possible – you will get the answer much faster then!

Hi FZ! Really love the work you're doing here. We're using Centrifugo as a pub/sub realtime messaging broker for some interactive functional services, including live-messaging.
Recently just switched engines, from Redis to Redis Cluster and lost "channels" capability.
Is there any plan to support "channels" call via cluster? Or, what would you recommend in lieu?

**"Show us an example of what you mean!"**
> An example can be useful, otherwise we're left guessing!

{"level":"error","error":"channels command not supported when Redis Cluster is used","time":"2020-08-07T03:58:39Z","message":"error calling channels"}
{"level":"error","error":"channels command not supported when Redis Cluster is used","time":"2020-08-07T03:58:59Z","message":"error calling channels"}

**Comment by sh3244** [comment]
For our production use case, it may still be a useful call up to thousands of users, and even more useful if indexed

**Comment by FZambia** [comment]
@sh3244 hello, yes, unfortunately this is not possible with Redis Cluster due to the fact that Redis Cluster does not support MOVED response for [PUBSUB CHANNELS](https://redis.io/commands/pubsub#pubsub-channels-pattern) command. This should definitely be emphasized in Centrifugo docs for Redis Cluster integration – sorry I missed this, will do.

In general (even with non-cluster Redis) Channels command does not scale very well for lots of channels due to the fact how it works internally (this is already written in docs).

Could you describe what problem are you solving using channels API? This can help to understand whether it's possible to solve it in a scalable way in future.

**Comment by sh3244** [comment]
Honestly, we just need an index of all currently active channels, as we use channel presence stats for live viewership data polling and notification dispatch from the backend.

We will pursue keeping our own live channel list instead for now...(will anyhow store in a redis cluster a list of channels [maybe centrifugo could do that? Since we already have full cluster implementation, just need a keyed set for it, right?])

**Comment by FZambia** [comment]
Just added a note to docs in d4df10ba5b345d9d109c9397d83c008a8979698e.

> Since we already have full cluster implementation, just need a keyed set for it, right?

Maybe... But to be fair I'd like to avoid adding more features to core Centrifugo Engine functionality, especially feature that already known as not scalable in this form. If you have time – maybe you can to write more details about your use case? Because I still don't see a full picture out of a single sentence scenario you provided.

**Comment by sh3244** [comment]
We have a livestreaming service that is composed of two services, a multi-video conference/broadcast service plus a messaging pub/sub service (centrifugo).

Multiple parties can interact and video conference in each room/channel.

For high level overview and stat calculation; as well as just having a safely stored (equally HA as centrifugo) reference for piping commands/data to channels, it would be nice to have a (paged?) channels call, since it is always changing in real-time.

**Comment by FZambia** [comment]
Thanks.

> For high level overview and stat calculation

I hope to solve this [with extensions like this one](https://centrifugal.github.io/centrifugo/pro/#real-time-connection-analytics-with-clickhouse). It will give users the possibility to use the power of fast analytical storage to investigate system state – channels, users, operations.

Also, I am evaluating the possibility to export channels into Redis data structure (ZSET maybe?) – but I am a bit worried about sharding concern here. Since channels data can't be easily sharded for convenient access over Redis native commands.

Clickhouse integration and Redis extensions (not for channels but a generic mechanism to create this sort of extension) already exist in MVP form but not merged into upstream since I was expecting them to be part of Centrifugo Pro version, but it turns out it's better to go [opencollective](https://opencollective.com/centrifugal) way. So I hope the code will be merged eventually.

> reference for piping commands/data to channels

Not sure I understand the use case here – could you extend this part? What `piping` means in this context?

**Comment by FZambia** [comment]
This can be fixed soon since `channels` method will use Survey under the hood - i.e. information will be gathered from all running Centrifugo nodes. Survey introduced in Centrifuge library v0.15.0, should be available in Centrifugo soon. Though the mechanism will be kept mostly for backward compatibility – it still won't scale very well as number of active channels grows.

**Comment by sh3244** [comment]
@FZambia sounds good.

By `piping` I just mean being able to index open channels and be sure that they exist (for broadcasting) without additional checks or indexes...in practice we keep duplicate indexes because of lack of channels support. I think ideally, it should be paged and indexed in realtime, so there should be no scaling issues aside from access size, right?

**Comment by FZambia** [comment]
>  I think ideally, it should be paged and indexed in realtime, so there should be no scaling issues aside from access size, right?

Actually I only aim to solve the lack of current channels API with different Engine implementations with channels over Survey method in v3. With mostly the same scalability concerns as now. This will also open a road for more variations of channels API - like using pattern/globing when calling it.

But the pagination is harder in terms of Survey (need to keep channels snapshot, have a cursor?) and is left for integration with ClickHouse or maybe another fast analytical storage in the future. I can only imagine `channels` usage for analytical purposes, not for relying on it as general runtime instrument to put business logic on top of. Every other use case I know about can avoid using channels.

**Comment by FZambia** [comment]
Updated HTTP API clients.for Go, PHP, Python to support latest `channels` API. Think it's ok to close now.
