### ISSUE TITLE
Non-obvious behavior in  client.HandleCmd

### ISSUE THREAD

**Issue by sl4mmer** [centrifugal/centrifugo#39]
**How to reproduce**
Using JSClient provide user or timestamp as integers
**What Happens**
Providing user or timestamp as integers causes following errors in client.HandleCmd respectively
````
json: cannot unmarshal number into Go value of type libcentrifugo.UserID
json: cannot unmarshal number into Go value of type string
````

**Solution**
Probably implict type cast in Js Client (and other lang-libraries) is the best solution...

**Comment by FZambia** [comment]
Hello! User ID can be a non number, for example MongoDB uuid-like identifier, so explicitly providing string as it happens now seems to be a right way.

I also don't think that we need to typecast timestamp because lots of libraries in languages return timestamp with microseconds while we need only seconds. The result of type cast can be even more non obvious. I think providing utility functions like the one [from centrifuge-go](https://github.com/centrifugal/centrifuge-go/blob/master/centrifuge.go#L18) is a better way.

**Comment by sl4mmer** [comment]
Then maybe let's just add a notice to JsClient documentation ?

**Comment by FZambia** [comment]
Yep, [commited](https://github.com/centrifugal/documentation/commit/aac967ce21fb59fa497864db8cba5344276d15ed)
