### ISSUE TITLE
[question] Multitenant implementation

### ISSUE THREAD

**Issue by zorca** [centrifugal/centrifugo#395]
**How to isolate multitenancy clients?**
> I am developing an application that uses the same code base for all clients and different databases. I've already tried out Centrifugo on one Laravel project and one Node.js-project and everything works fine. How can I create a system that will isolate the Centrifugo channels for each client? It would seem a good solution to use namespaces for different clients. But I want to go further and completely isolate each client so that they can create private and public channels with namespaces.

…

**Tenancy for Laravel**
> This is an example of a package for Laravel that uses database differentiation for different clients: https://tenancyforlaravel.com/. Each tenant has its own ID. I would like that when accessing Centrifugo, you can set this ID and thus access your own set of channels. This is the system used in another project: [Larasocket](https://larasocket.com/).

…

**Comment by FZambia** [comment]
@zorca hello:)

I suppose in most cases when you need multitenancy you can run separate Centrifugo for each tenant. This way once application won't affect another one. Not sure how this fits your case though – can you elaborate on this? 

Do you have any specific API for multitenancy in mind? There was a proof of concept done before (but it was not merged into upstream), but I'd like to see first how you personally imagine multitenancy support in Centrifugo? Could you show abstract examples – how to connect, how to publish. Then I'll be able to extrapolate this to the work done before and find out whether we think about the same thing.

> I want to go further and completely isolate each client so that they can create private and public channels with namespaces.

Namespaces can't be created dynamically by clients – it's supposed to be created by application developers. Or do you mean that you want to isolate each client to its tenant but **reuse** namespace configuration?

**Comment by zorca** [comment]
Good afternoon! And greetings from Saint Petersburg! :) I noticed that when automatically creating a node in Centrifugo, the node is assigned a UUID. The same thing happens when creating a tenant (client isolated application) in the Multitenancy package. Ideally, I would like to create a node with exactly the same UUID as the tenant and publish to this node from tenant.
Then subscribing to the channel, I will send the tenant token and its UUID in each request, as its done in Larasocket requests:
`wss://ws.larasocket.com/?token=3|6JftR8KjsIS*******&uuid=6a027f38-8e45-43bd-90db-9cbf******`

**Comment by FZambia** [comment]
> I would like to create a node with exactly the same UUID as the tenant and publish to this node from tenant.

Then I suppose you can create Centrifugo instance per tenant manually on a site subdomain (on load balancer level)? Like `<TENANT-UUID>.your-site.com` and connect/publish to that instance? Especially if you want to handle client connections from different apps on different Centrifugo nodes.

**Comment by FZambia** [comment]
After considering this more I think that multitenancy is nice to have in general, but I believe that this quickly becomes an antipattern if isolation is not done right. To make it right we should also implement the following:

* Resource isolation – to prevent one app affecting the performance of another app, I don't think this is reasonable to have inside Centrifugo since this is a very difficult task that should be solved on the operating system level
* Make different tenants visible in metrics – this requires refactoring of the entire code base

What we can do in Centrifugo though is to introduce an extra layer of permissions for channels, one possible way is like this:

1) Define new option `channel_env_delimiters` to sth like `[]`. This will enable the rules from the following points.
2) Include `env` string as JWT claim or return in `credentials` from connect proxy, for example `"env": "site_01.com"`
3) After this client will only be able to subscribe or publish to `[site_01.com]namespace:channel` - i.e. only to channels that start with its environment set on connect.
4) `[site_01.com]` won't affect namespace configuration - i.e. will be stripped down when looking for a channel namespace.
5) When publishing application will have to use full channel names – i.e. `[site_01.com]namespace:channel` in this case.

Not sure this is the best API, just an approach that have already araised before.

**Comment by FZambia** [comment]
Closing for now since no real interest from a community at the moment, may come back to the idea above in the future.
