### ISSUE TITLE
[question] Integrate Centrifugo with nodejs express-session

### ISSUE THREAD

**Issue by car1ot** [centrifugal/centrifugo#405]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!

I have the node js express app, which uses express-session to auntificate users!

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

I need to auntificate users with centrifugo. Is it possible to use express-session?

**Comment by FZambia** [comment]
Hello!

Default mechanism of authentication in Centrifugo have always been JWT. But since v2.5.0 Centrifugo has connect proxy - where it passes connection requests coming to Centrifugo to application backend. Centrifugo copies original request headers so application backend has a chance to authenticate connection request in the same way it does for regular HTTP requests. **You may need to run Centrifugo on subdomain** to make browser pass your authentication cookie with request to Centrifugo. Here is a link to connect proxy docs: https://centrifugal.github.io/centrifugo/server/proxy/#connect-proxy

Did you know about it? Did you try it? I don't think I can help specifically with `express-session` – but integration should be straightforward.

Alternatively you can also use JWT with expiration approach which gives some performance benefits on scale – though I suppose you already rejected this way of integration and want native auth.

**Comment by FZambia** [comment]
@car1ot hello, I am closing an issue since no other questions followed and nothing actionable left here. Please reopen if you will have another related question. Also don't forget about community chats (links in README)
