### ISSUE TITLE
[feature] RPC proxy: return status and body for any request (not only status 200)

### ISSUE THREAD

**Issue by Tsmar** [centrifugal/centrifugo#407]
Hi!
I develop REST API and any responses with errors has additional information in response body (json)
Also it's great way for using two version of API requests: via HTTPS to my API or via WSS with RPC proxy by centrifugo
Now centrifugo proxy to me "Internal Server Error" and error code 100 or similar )
What do you think about that?

PS sorry for my english

**Comment by FZambia** [comment]
Hello @Tsmar !

I don't think this is worth adding to Centrifugo since you can implement a similar thing on your backend side with a basic adapter. All you need to return custom codes to a client - just wrapping your errors to a payload returned from the RPC call and inspect this in a way you need on client-side.

Alternatively, you can return a custom error - see https://centrifugal.github.io/centrifugo/server/proxy/#return-custom-error. Though keep in mind:

> Application should use error codes >= 1000, error codes in range 0-999 are reserved by Centrifugo internal protocol. Error code field is uint32 internally.

It will be pretty hard to fully follow REST spec for this level of communication: not only regarding returning custom errors (since we already have a semantically different error layer). But also, REST involves using custom methods: GET, POST, PUT etc – this is hard to achieve since every method should be described and use a different way to execute. For the current RPC format, there is no such separation - everything has a method name and payload - which just simplify things a lot. But as I said - I think you still can write an adapter code to have both HTTP REST and RPC over WebSocket existing together.

**Comment by Tsmar** [comment]
Hi! Custom errors with >=1000 is possible too, thanks!
