### ISSUE TITLE
[feature] add grpc stream support for `presence`

### ISSUE THREAD

**Issue by alexshavelev92** [centrifugal/centrifugo#425]
Default GRCP message size is `4MB`. If only use `user` + autogenerated `client` ~30k users fill feet in it at `presence` request. 

To not bother users to watch and configure message size I propose to add `GetPresenceStream`.

If you don't have any objections - I think can implement it

**Comment by FZambia** [comment]
Hello!

Interesting approach. But I am not sure it's a good idea since presence information is not a stream in its nature. So I suppose the best way is configuration at the moment.

Though I'd like to hear your use case for presence – how do you use this information? As far as I remember it's already mentioned somewhere in docs that current presence and join/leave messages design mostly fit well channels with reasonably small number of active subscribers. Hacking on a way to deliver presence from Centrifugo to application without solving how Centrifugo asks this from broker (still one chunk of data) is not the right thing to do in my opinion. Maybe you need to find an alternative approach to your task.

One thing that could help in some cases is real-time analytics - like mentioned [here](https://centrifugal.github.io/centrifugo/pro/#real-time-connection-analytics-with-clickhouse). Though I am not sure how this can fit your use case.

**Comment by alexshavelev92** [comment]
uh, haven't mentioned these details about `presence` in FAQ before
