### ISSUE TITLE
Is the documentation outdated?

### ISSUE THREAD

**Issue by kamikazechaser** [centrifugal/centrifugo#427]
From the docs:

> The only two fields required are token_hmac_secret_key and api_key. 

- From https://centrifugal.github.io/centrifugo/server/configuration/

However Centrifugo boots up and works (I am using proxy to backend mode) without the `token_hmac_secret_key`. Is it safe to assume that all config options are optional?

**Comment by FZambia** [comment]
@kamikazechaser hello!

Thanks for pointing, turns out this is really the outdated statement, with proxy it's possible to go without `token_hmac_secret_key` and with publish proxy `api_key` can also become optional in some setups (where HTTP API not used at all).

Though both config fields required to start with traditional Centrifugo setup – will try to change doc somehow to reflect possible ways to go without them.

**Comment by FZambia** [comment]
Added a note in f6c13e3e3894051a02c72d5058a4506bf7a6d4f3 - hope it makes things more clear

**Comment by kamikazechaser** [comment]
Looks good!
