### ISSUE TITLE
[question] How to detect user on join/leave personal channel on server side

### ISSUE THREAD

**Issue by GNURub** [centrifugal/centrifugo#428]
{
		"token_hmac_secret_key": "...",
		...
		"user_subscribe_to_personal": true,
	    "user_personal_single_connection": true,
	    "user_personal_channel_namespace": "personal",
	    "namespaces": [
	      {
	        "name": "personal",
	        "presence": true
	      }
		 ]
	}

	// server.js, without jwt?
	const centrifugo = new Centrifugal('ws//...');
	const personal$ = centrifuge.subscribe('personal');
	personal$.on('join', (ctx) => {
		// Actions... Every time a user joins.
	})

**Comment by FZambia** [comment]
@GNURub hello!

The only way to listen on join/leave messages on a server-side is to use one of the available client protocol clients. Though this means that a server connection will be a channel participant too. This is not a common use case, thus it was never supposed to work for a server-side.

Maybe if you describe your use case in detail – I'll be able to think about possible alternatives or improvements.

**Comment by GNURub** [comment]
Hello, and thanks for your answer.

So, I can listen the publications, but not when a user connects?

	centrifugo.on('publish', (ctx) => ...);

A solution could be to subscribe the server to the main channel, and client publish a connection event.

**Comment by FZambia** [comment]
Sorry - I lost a point, could you provide more context? You can listen to publications using client API, join/leave is also part of client API. 

Usually when someone needs tricks like you described this is a signal of attempt to build sth on top of Centrifugo which was not put into Centrifugo design.

**Comment by GNURub** [comment]
I want to detect when user connects on 'user channel' (using `user_subscribe_to_personal`), catching the `join` event on server side for this channel as it happens with [publish](https://centrifugal.github.io/centrifugo/server/server_subs/) event.

Ex. An user join on `personal#123`, then server side send all notifications from db using this channel to user.

The question is if is possible to listen the events join/leave on personal channels from server side?

I'm sorry if I didn't explain myself correctly. :)

**Comment by FZambia** [comment]
Idiomatically for Centrifugo you need to send all personal notifications to Centrifugo regarding the fact whether or not user currently online. Centrifugo will just drop a message if channel has no active subscriber. This is how PUB/SUB usually works.

Answering to your question - the only way to listen join/leave messages on server side is using one of our client libraries - i.e. faking server as being one more client subscribed to that channel. But I'd avoid going this way - it just an abnormal usage, and does not scale well.

One more option is using connect proxy - on connect you can subscribe client to personal server side channel. At this point you know that client connected and subscribed - so you have Join analogue. Though you won't have disconnect - Centrifugo does not have any disconnect hooks and it won't in the future. I explained why in documentation FAQ. Though it's possible to use refresh proxy to periodically tell your backend that connection is still alive. This way you will be able to approximately decide that user went offline since you have not received refresh requests for a long time. This should work - but I still think you can simply publish everything to Centrifugo and let it decide whether to deliver message to subscribed active client or drop it.

**Comment by GNURub** [comment]
Thank you very much for the reply. Great job with centrifugo! ;)
