### ISSUE TITLE
[feature] Ability to modify original message in Publish proxy

### ISSUE THREAD

**Issue by matpuk** [centrifugal/centrifugo#439]
Hello!

Currently, Publish proxy can only allow/deny a message. How about to make it possible to modify original message?
For example, if I need to replace bad words in a message before allowing it to go to a channel.

**Comment by FZambia** [comment]
Hello @matpuk 

Looks nice to have, this can be done by extending [PublishReply](https://github.com/centrifugal/centrifuge/blob/v0.16.0/events.go#L162) in Centrifuge library with `data []byte` field - then if a non-nil data returned in reply – publish it to a channel instead of original payload. Then we need to update Centrifuge dependency here in Centrifugo and make publish proxy use this new field. 

A possible workaround available for now: you can use RPC proxy. Call RPC with method like `publish` and payload which has desired channel and data, then on your backend side validate RPC and call Centrifugo Publish HTTP API, then return success to RPC request. This involves extra HTTP call but can help until we add this feature.

Please give me know whether this all sounds reasonable.

**Comment by matpuk** [comment]
Hello!

Well, the problem with HTTP API is that it's impossible to set 'info' part of the message. I'd like to preserve original 'info' and modify message's body. Or add custom meta into existing 'info' dictionary.

**Comment by FZambia** [comment]
> the problem with HTTP API is that it's impossible to set 'info' part of the message.

Yep, this is not possible at the moment. BTW theoretically there is no blocker in adding possibility to set custom info in HTTP API - this is already possible in Centrifuge library. Though adding custom info in Centrifugo HTTP/GRPC API is sth I'd like to avoid until no other way really exists - since it ruins semantics. So for this case I suppose just adding a modified data field to publish proxy is the most straightforward way.

As a possible workaround - you can use RPC, publish API, but extend payload you publish into a channel with some additional `info` object (since you most probably can construct it on a backend). This will require adapting client side though. Maybe you mean exactly this when saying:

> Or add custom meta into existing 'info' dictionary.

**Comment by matpuk** [comment]
I understand the problems you described and think that adding possibility to modify payload in Publish proxy will be enough.

**Comment by FZambia** [comment]
@matpuk hello, done in #441, should be available in next Centrifugo release.

**Comment by matpuk** [comment]
Hello!

Great news! Thank you very much!

**Comment by FZambia** [comment]
Released with [v2.8.5](https://github.com/centrifugal/centrifugo/releases/tag/v2.8.5)
