### ISSUE TITLE
[Question] how to get user when refreshing centrifugo token (token auth)

### ISSUE THREAD

**Issue by aryan340** [centrifugal/centrifugo#445]
In my django application, I am using token authentication (and not sessions).
So I have a doubt. How can I know which user is requesting the token to be refreshed when I get a request to the endpoint?

![image](https://user-images.githubusercontent.com/69184573/116189836-2d551780-a747-11eb-8c07-4f7601a612c7.png)

this is how clients authenticate with my django api.
They attach an authorization header with all their requests.

example,
```
Authorization: Token xxxxxxxxxxxx
```

**Comment by FZambia** [comment]
Since request goes to your endpoint from a client-side you can always detect the user ID using standard authentication mechanisms you already have in your app. If you asking about a way to add headers to refresh request then [take a look at available options](https://github.com/centrifugal/centrifuge-js#refreshendpoint).
