### ISSUE TITLE
[feature] Access to channel offset and epoch

### ISSUE THREAD

**Issue by gazugafan** [centrifugal/centrifugo#446]
From the discussion here: https://github.com/centrifugal/centrifuge-js/pull/44#issuecomment-827998601

It would be nice to be able to get a channel's ```offset``` and ```epoch```--especially after publishing a message. Ideally, I'd like the publish command to respond with the newly published message's offset and epoch--similar to how NCHAN works. Or perhaps there could be a new command to retrieve a channel's current offset and epoch?

This would help solve the problem where, after loading the application state during the initial page request, messages are published (and missed) in the few seconds before the client can establish a subscription connection.

Instead, we could send the current ```offset``` and ```epoch``` along with the current application state during the initial page request, and then include this offset and epoch when the client subscribes. 

It would be extra nice if the centrifuge-js (and other) client libraries could accept an ```offset``` and ```epoch``` right in their ```subscribe``` methods--automatically retrieving and playing back any messages missed afterwards. I think the existing ```history``` method is probably enough to accomplish this already, but that would require a little extra work and I'd be worried the timing might not be quite perfect.

**Comment by FZambia** [comment]
Done in v3, [introduction blog post](https://centrifugal.dev/blog/2021/08/31/hello-centrifugo-v3).

Offset and epoch now returned in publish result if channel stream has history enabled. 

@gazugafan, centrifuge-js 2.8.0 also contains a way to access StreamPosition in `SubscribeSuccessContext` (in channels with history enabled and `position` or `recover` options on). And a way to subscribe from certain `StreamPosition` and thus [manually activate recovery process](https://github.com/centrifugal/centrifuge-js#subscribe-since-known-position). Also it's possible to bypass recovery mechanism and implement manual message recovery from history stream using history iteration API (available in client and server API). Feel free to reach me out with any questions – would be awesome to know whether this all worked for you eventually.

**Comment by gazugafan** [comment]
Amazing! Excited to try out v3 soon. Will report back when I do :D

**Comment by FZambia** [comment]
Closing, feel free to continue writing here in case of any feedback.
