### ISSUE TITLE
Django-instant update: support for Centrifugo 2 in Django

### ISSUE THREAD

**Issue by synw** [centrifugal/centrifugo#452]
Hi,

I finally updated [django-instant](https://github.com/synw/django-instant) for Centrifugo 2. I added an example repository showing how to use it with a backend and a frontend. I configured it to use the Centrifugo demo instance by default so that it's easier for the users to try it out. @FZambia do you mind if I use this instance in my demo repository: https://github.com/synw/django-instant-example ?

**Comment by FZambia** [comment]
@synw hello, nice to hear from you!

Yep - I noticed this yesterday and already added a link to django-instant to docs in 0274408884f3aa431e321c22b609d5f15dd6603f. Very good news! I don't mind using demo instance of Centrifugo in your demo project - though I think a good idea would be mention this in django-instant-example readme and provide a configuration required to run Centrifugo locally since Heroku Centrifugo demo is black box for users. Demo instance has the configuration similar to this one:

```json
{
  "v3_use_offset": true,
  "token_hmac_secret_key": "secret",
  "admin_password": "password",
  "admin_secret": "secret",
  "api_key": "api_key",
  "allowed_origins": ["*"],
  "publish": true,
  "anonymous": true,
  "join_leave": true,
  "presence": true,
  "history_size": 100,
  "history_lifetime": 300,
  "history_recover": true
}
```

I.e. most channel options enabled on top-level.

**Comment by synw** [comment]
I put a notice recommending to install a local server and kept the default Heroku config for convenience. Thanks. I mentioned the config you show above for user info, but my example works out of the box with a generated genconfig file anyway
