### ISSUE TITLE
[feature] Scale at most once PUB/SUB without external broker with embedded Nats server

### ISSUE THREAD

**Issue by sash2222** [centrifugal/centrifugo#479]
Hey!
But what if we add the ability to scale with memory engines to the centrifuge?
There is such a project, which is already quite mature, https://github.com/buraksezer/olric, in fact, this is a KV cluster with Raft inside. And it has one great feature - it can work like a built-in library.
1. We need to build it into a centrifuge
2. to teach the centrifuge to transfer parameters to it to build a cluster (ectd, etc.)

**Comment by buraksezer** [comment]
Hi,

Thank you for mentioning Olric. I'm the author of that project. Olric doesn't use Raft. Olric is an AP (eventually consistent) product in the context of the CAP theorem, which employs the combination of primary-copy and optimistic replication techniques. With optimistic replication, when the partition owner receives a write/delete operation for a key, applies it locally, and propagates it to the backup owners.

Here is some further information about the design: https://github.com/buraksezer/olric#consistency-and-replication-model

If you have any further questions, please feel free to ask me.

**Comment by sash2222** [comment]
My deep apologies, I apparently treated the documentation superficially, now I understand why there is ectd, consul and other coordination systems.
Nevertheless, by integrating Olric into a centrifuge, we can get the desired effect of memory scaling with one dependency - consul, etc.

**Comment by FZambia** [comment]
@sash2222 hello.

In general, you are thinking in the direction I personally would like to move too. I already tried to approach creating a built-in engine based on Raft, which comes with Centrifugo itself (though as a subcommand – to scale dealing with connections and broker part separately) and optimized for Centrifugo task. But while I made sth working the work was too hard to finish in short terms – there were many caveats to solve and many to research. So I decided to postpone it until better times at prototype stage.

Regarding your suggestion – Olric looks interesting and I once read about it before. But it will not allow implementing all Centrifugo engine capabilities. Applied to Centrifugo – it's only possible to use it as a PUB/SUB broker (without our history and presence features). I.e. similar to our Nats integration. But the important thing is that Olric does not support ordered delivery (since it's based on gossip-like protocol I suppose, @buraksezer – maybe you can tell more precisely?) – this is a crucial thing for a Centrifugo broker.

That said – personally I'd like having built-in in-memory scalable engine without relying on third party server (i.e. Nats, Redis, Tarantool we currently have) – but I believe it should be Raft-based and support all our engine features/guarantees.

If you want PUB/SUB scalability without external dependencies and not worried about history/recovery/presence, then embedding Nats server into Centrifugo seems more reasonable to have. Requires research though.

What do you think?

**Comment by sash2222** [comment]
I probably also agree that RAFT is more appropriate here, since it has no dependencies. And at first I wanted to offer other options, but I realized that the internal mechanics of the centrifuge apparently strongly depends on the capabilities of the scalability engines.
Therefore, embedding NATS looks reasonable. It might even be possible to inline NATS JS (essentially the same code) to ensure persistence.

**Comment by FZambia** [comment]
> It might even be possible to inline NATS JS (essentially the same code) to ensure persistence.

Unfortunately impossible – see https://github.com/nats-io/jetstream/issues/266 I once opened but it was closed.

**Comment by FZambia** [comment]
@sash2222 hello, I renamed an issue title based on a discussion we had. Is this fine? Could you please tell me whether you are interested in trying out embedded Nats (i.e. scale PUB/SUB but do not have history and presence features)? Do you have a real use case for it or just researching things?

Regarding full-featured zero-dependency built-in in-memory engine: I'd like it to happen, bit this seems a pretty long story – I think this should be similar to Nats Jetstream system (+ presence in ideal world). Requires research and implementation – as this is really a non-trivial thing to do. Any help with making it happen is much appreciated!

**Comment by FZambia** [comment]
After embedding Nats server in #481 and researching a bit I have some doubts about the idea:
1. Centrifugo nodes should scale well given more connections, with embedded Nats each Centrifugo node will become Nats cluster node – since it's a full mesh internally this will result in many connections between nodes - thus scalability will be pretty limited. Current approach when nodes scale separately from broker (whether it's Nats, or Redis, or KeyDB, or Tarantool) do not affect broker scalability in such way. To sum up: having broker separate to scale Centrifugo nodes and broker itself separately is a preferred approach. Maybe Nats leafnodes and gateways can solve this concern – but I am not sure about this at the moment and that's a massive configuration/maintenance increase anyway. 
2. Embedding Nats will require having a different approach inside existing Centrifugo Helm chart – i.e. we should use  StatefulSet for nodes (to construct full mesh). This is possible to configure – but goes agains the current design a bit.
3. Embedding Nats significantly increases Centrifugo binary size (24MB -> 30MB). Not a problem in general, but dependency is pretty heavy.

That said – I am not sure that Centrifugo will go this direction without clear motivation that is needed. Deploying separate Nats server is pretty simple thing to do and scales better – thus not sure having zero-dependency outweighs concerns above.

**Comment by FZambia** [comment]
Closing due to the reasoning in comment above. Maybe we can come back to this in the future if we get the more clear motivation why it's needed.

Still hoping that we will have our own broker backend – but it should run separate from nodes that handle connections.
