### ISSUE TITLE
[question] Suggestions to handle a particular usecase

### ISSUE THREAD

**Issue by srivikraman** [centrifugal/centrifugo#494]
Hi, I need some suggestion 

**Overview:** 
**Backend:** we are getting a stream of data from third party provider and storing in database
**Data passing to frontend client:** we are using REST API to provide old data from database and websocket(centrifuge) to provide live data

**Current Usecase:**
1. We have channel topic at particular stock level(e.g: reliance, tata...)
2. As we already discussed, we exposed rest api for old stock data and websocket for live data

**Current Behaviour(Problem in our application):**
 For some reason, frontend is having 60 seconds delay(rarely happening) for subscribing to new channel, so some data missing,
We are planning to send last 60 sec data to frontend via websocket But how! Here comes the main below question.

**Main question:**
**Does Centrifuge library support sending data to particular client alone in common channel ?**

Thanks for your time in reading this.

**Comment by FZambia** [comment]
Hello, @srivikraman 

Centrufuge/Centrifugo channels allow sending the same content to all subscribers without any possibility to filter out some messages. To send messages to a particular user subscribe user to a personal channel and send message to it. I.e. common messages to a common channel, personal messages to a personal channel.

Some related information can be found [in FAQ](https://centrifugal.dev/docs/faq/index#any-way-to-exclude-message-publisher-from-receiving-a-message-from-a-channel).

If you are using [connect proxy feature](https://centrifugal.dev/docs/server/proxy#connect-proxy) then take a look at connect proxy result `data` field - it allows to send some initial data to a client upon connect. And also the same is valid for [subscribe proxy](https://centrifugal.dev/docs/server/proxy#subscribe-proxy) - it's also possible to send some initial `data` upon subscribe in subscribe reply - so that this data only will go to the client that issued subscribe request.
