### ISSUE TITLE
[question] How to refresh token centrifugo

### ISSUE THREAD

**Issue by ducthach1401** [centrifugal/centrifugo#523]
I read centrifugo document and how to refresh token: 

> For example, a Javascript browser client will send an AJAX POST request to your application when it's time to refresh credentials. **By default**, this request goes to **/centrifuge/refresh** URL endpoint. In response your server must return JSON with a new connection JWT

Url endpoint is created by automatic or manual because you wrote "By default"

Thank you very much

**Comment by FZambia** [comment]
Hello!

`/centrifuge/refresh` is an endpoint which should be defined on your application backend server, in endpoint handler you should return a new token for a user (user is authenticated by your standard application session mechanism, since endpoint is part of your backend).

For example, [here](https://github.com/centrifugal/examples/blob/master/v3/python_tornado/main.py#L127) is how such a handler is defined in Tornado-based application backend server (it's very basic example as the user is hard-coded there).

I do not understand how endpoints may be created automatically. Of course it's up to you to define it, we only have default address which is called.

When the time comes, centrifuge-js calls the endpoint (you can change this endpoint address using [options](https://github.com/centrifugal/centrifuge-js/tree/2.8.5#refreshendpoint) of centrifuge-js). It's also possible to override the way how `centrifuge-js` retrieves a token using `onRefresh` option of `centrifuge-js` if the default AJAX call does not fit your needs.

If you still have questions please join our community chats and ask for help there.
