### ISSUE TITLE
[feature] Limit number of connections in a single server

### ISSUE THREAD

**Issue by jvilhuber** [centrifugal/centrifugo#544]
**Is your feature request related to a problem? Please describe.**

I'm worried about scaling: each connection uses some memory (more if TLS is enabled), so given limited memory on a server (ec2 instance or other VM), I'd like to avoid OutOfMemory crashes when too many connections are directed to a specific server.

A server should have some notion of maximum connections (or max memory usage) and reject any connections above the limit.

**Describe the solution you'd like**.

Perhaps some http middleware that counts active connections, and rejects any new ones. This is easy in the low-level use with gobwas/ws since you can do the rejection after the Accept (and thus before any TLS setup). Not sure how to do this in the ServeHttp concept easily.

...

**Comment by FZambia** [comment]
@jvilhuber hello, in general this seems reasonable, actually I wrote the same advice in [blog post here](https://centrifugal.dev/blog/2020/11/12/scaling-websocket#os-tuning), but it was not added to Centrifugo.

A couple of questions:

1. Do you expect client to continue reconnecting after getting disconnected due to the limit?
2. What is your plan to handle a situation when a server is fully filled? Are you going to monitor number of conns and manually add servers? Or some automated way to spawn more Centrifugo nodes in this case? What's the recovery strategy you thinking about? Long-lived connections come with unique trade-offs so curious about your experience here.

**Comment by jvilhuber** [comment]
For (1) yes. In my use-case, I won't be using a load-balancer (too costly) and so clients will get a list of URL's they should try. If one doesn't work, try the next (it'll likely be more complex than that, but you get the idea).
If someone uses a load-balancer and auto-scaler (AWS?) then scaling can be automated and the clients won't need to know. The important thing is that the servers WILL NOT CRASH (due to OOM).
For (2), yes. Monitoring and some automated/manual (TBD?) way of adding more servers to the list.

**Comment by FZambia** [comment]
Thanks,

Actually `netutil.LimitListener` does not do what we want here, it blocks the incoming request instead of dropping it. So I suppose the best way we can do with std lib is act on middleware level. @jvilhuber check out #546 - does it look sufficient?

**Comment by jvilhuber** [comment]
Yea that looks like it would work. I added one minor suggestion.

**Comment by FZambia** [comment]
Part of [v4.0.1](https://github.com/centrifugal/centrifugo/releases/tag/v4.0.1)
