### ISSUE TITLE
[question]  golang client that also compiles to wasm ?

### ISSUE THREAD

**Issue by gedw99** [centrifugal/centrifugo#557]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!

I am needing a golang client that works as wasm and non wasm. 

The current go sdk does not support wasm .

...

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

Example would be supporting SSE or websockets in the go sdk via build tags. 
...

**Comment by FZambia** [comment]
Hello @gedw99 ! Yep, current Go SDK does not work in wasm env. Would be awesome to have it of course, though no understanding about required effort at the moment. I opened an issue in `centrifuge-go`: https://github.com/centrifugal/centrifuge-go/issues/67, will be interesting to try, but can't give any promises or ETAs for it unfortunately.

**Comment by FZambia** [comment]
I did some research in https://github.com/centrifugal/centrifuge-go/pull/68 - I made it work and functional. More details in PR description. I am a bit skeptical at this point since wasm binary is 12 MB, not sure anyone wants to put file of this size to the frontend app. That pr also describes experiments with `tinygo` - there are some limitations which prevent `centrifuge-go` to be used with it.

Closing this issue, lets discuss inside https://github.com/centrifugal/centrifuge-go/issues/67 or https://github.com/centrifugal/centrifuge-go/pull/68
