### ISSUE TITLE
connection to Centrifuge 2.7.6 

### ISSUE THREAD

**Issue by Echora-1** [centrifugal/centrifugo#563]
problems connecting to a private channel
```
import Centrifuge from 'centrifuge/dist/centrifuge.protobuf';

const centrifuge = new Centrifuge('wss://web.tbcc.info/ws?format=protobuf')

centrifuge.setToken("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJpbmZvIjoiMSIsImV4cCI6MTY2NDk1OTk1MH0.0Xn9YvS1eHUGsBusA2iKhuXnDSgF6VXN0HaNe3UkLaY");

 centrifuge.on("publish", function(ctx) {
    console.log(fromBytes(ctx.data));
 });

centrifuge.connect();

```

then I trigger the creation of a message in the channel through a request

```
http://95.217.65.204:18888/v1/get_address?trader=183&platform_id=11&currency=TBCC 

Authorization: Bearer vCEKAUnD4Tm6bx7dG0dWyKA1boURgkh12EPR926eOm1Z5zNlBHnIhTcZpFrPF4cPHHtv17tBWR2BlVje
```

waiting for data type

```
{
    "currency": "TBCC",
    "platform": "bnb",
    "address": "0xee9efaad88417ff78c1f207f1dd19a2478b3eb7c",
    "error_code": null,
    "error_message": null
}
```

in my case nothing comes

I will be grateful if you tell me where the error is

**Comment by FZambia** [comment]
Hello, so sorry - I don't have enough capacity to help with Centrifugo v2 use cases these days. Probably someone from the community rooms have time to dig into this.

In the example you are showing you are not subscribing to a private channel – only connecting to Centrifugo. And using server-side subscriptions to consume a message (`centrifuge.on('publish')`). I suppose when subscribing to a private channel in Centrifugo v2 you need to create Subscription object and follow [centrifuge-js v2 private channel docs](https://github.com/centrifugal/centrifuge-js/tree/v2#private-channels-subscription). But can not figure out the root cause out of the information you provided.
