### ISSUE TITLE
[question] I have error and I cant fix it.

### ISSUE THREAD

**Issue by ax-ross** [centrifugal/centrifugo#571]
Hello, I using centrifugo + nginx + laravel + vuejs via docker compose. I used this guide for settings my app https://centrifugal.dev/blog/2021/12/14/laravel-multi-room-chat-tutorial and tried adapt it for centrifugo v4. 
I have: 
"centrifuge-js": "^3.0.1",
"denis660/laravel-centrifugo": "^3.0",
centrifugo/centrifugo:v4,
laravel 9

When I try to connect to channel, I get an error in my docker compose logs: 

centrifugo       | {"level":"error","client":"c0442434-aa3c-4fa6-8521-0c6b4f756890","error":"HTTP request error: Post \"http://nginx/centrifugo/connect\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","time":"2022-10-22T08:13:52Z","message":"error proxying connect"}
centrifugo       | {"level":"info","client":"c0442434-aa3c-4fa6-8521-0c6b4f756890","code":100,"command":"id:9 connect:{name:\"js\"}","error":"internal server error","reply":"id:9 error:{code:100 message:\"internal server error\" temporary:true}","user":"","time":"2022-10-22T08:13:52Z","message":"client command error"}
I tried to set timeout in my js:
(
const centrifuge = new Centrifuge('ws://127.0.0.1:8000/connection/websocket', {
    debug: true,
    timeout: 20000
});
and in my centrifugo config:
"proxy_connect_timeout":  "10s"
but its not working for me.

Please, help me to fix it.
Below I attach my configs:

nginx: https://pastebin.com/k55iqvqs
centrifugo: https://pastebin.com/wi3AcEz6
docker-compose: https://pastebin.com/qah9kgeT
js: 
![изображение](https://user-images.githubusercontent.com/103892341/197330116-74bcfbcc-5a60-403a-82f4-bcf18959548b.png)
![изображение](https://user-images.githubusercontent.com/103892341/197330123-78442773-7261-4d04-b821-e461c4334c46.png)

**Comment by FZambia** [comment]
Hello!

The only thing I noticed here is that your app in docker-compose does not expose any ports. I suppose it should expose 9000? Probably it's not the root cause, it's very hard to debug without a way to reproduce - if the idea with the port won't work out please post this all as a Github repo and I'll try to look.

**Comment by ax-ross** [comment]
Unfortunately, its didn't helped me(
Can I add you to my private repo to you can run docker compose?

**Comment by ax-ross** [comment]
Many hours left, I fix this problem... I changed host  proxy_connect_endpoint in centrifugo config file from nginx to webserver (yes, I'm so bad(( ). But not I have 2 new problems... 
First, I get 419 error when I'm trying to connect to /centrifugo/connect, It's mean, what csrf tokeт was not transferred (I have "X-XSRF-TOKEN" header in my proxy_http_headers centrifugo config now, but I think csrf token not sent from centrifugo-js). For test, temporarily, I disable csrf protection for this route.
Second, when I disabled csrf protection, I added test print on publication event: 
![изображение](https://user-images.githubusercontent.com/103892341/197358720-986b19aa-bfdb-4d16-93e2-656c5bd6df40.png)

But I don't get any message in my console. And no errors. This is my publish method of RoomController:
![изображение](https://user-images.githubusercontent.com/103892341/197358778-e587ea11-1b43-43eb-ac4a-fb9d1d1baaca.png)

Sorry for wasting your time, but its turned out to be hard for me(

**Comment by ax-ross** [comment]
Note. If I use publish to personal channel instead, it's working, but I think it's will be sent messages to all users from all chats.
![изображение](https://user-images.githubusercontent.com/103892341/197359163-4b43e70c-a1fd-451a-bf59-b58c564efb59.png)

**Comment by FZambia** [comment]
Since Centrifugo issues a POST request to your backend when using connect proxy – then Laravel may automatically require CSRF token to be presented in request headers. But since this is not a form submission,  you can safely disable CSRF check for the endpoint which serves connect requests from Centrifugo. Centrifugo uses POST just as a way to pass some JSON body in convenient way.

You can't control headers which are sent in WebSocket case, your browser only sends cookies for the target domain, and that's all. There are possibilities though to append CSRF token to Centrifugo endpoint URL params for example, then on transform it to header on load balancer or reverse proxy level. But I don't think you need to do this in this case.

**Comment by FZambia** [comment]
Closing, please use community rooms when asking for a help.
