### ISSUE TITLE
[bug] Server accepts websocket connections with client_insecure set to false

### ISSUE THREAD

**Issue by gs4l** [centrifugal/centrifugo#639]
**Describe the bug**: Server accepts websocket connections with client_insecure set to false
**Versions**: centrifugo version 4.1.2

The centrifuge library first upgrades the websocket connection request and then waits for the next frame to get the connect token, verifies it, and closes the connection if the token is invalid. This is handled by the client library centrifuge-js as it immediately sends a data frame with connect token.

If a raw websocket connection is opened using some other library (example ws in nodejs), the server accepts the connection and waits for the next frame. After some time the server closes the connection. This allows opening anonymous websocket connections to the server and a script trying to open websockets connection in infinite loop can take the server down resulting in denial of service attacks.

The below code snippet is able to open a connection with client_insecure set to false

```
import WebSocket from 'ws';

const ws = new WebSocket('wss://server_url/connection/websocket');

ws.on('error', console.error);

ws.on('open', function open() {
    console.log("open");
}
```

**Comment by FZambia** [comment]
Hello,

The behaviour is expected - this is by design since authentication details passed in the first frame from client to server. Centrifugo closes unauthenticated connections (and connections that have not sent connect frame at all) after some time (25 seconds by default). This time may be tuned using `client_stale_close_delay` option. So if you want - you can reduce it to something like network RTT.

But in general, you need to use additional  infrastructure to properly protect WebSocket server from DDOS. For example, configure Nginx and limit number of connections per IP address. Or other ways on network level.

**Comment by gs4l** [comment]
Hello,

Thank you for the clarification.

I wonder if the same is included in the documentation. Because the people using centrifugo out of the box would most likely be unaware of this behaviour and might not apply the necessary configurations to properly secure the server.

`client_insecure=false` by itself sounds like the server will not upgrade any anonymous connection requests or with requests invalid token.

**Comment by FZambia** [comment]
Yep,

The `client_stale_close_delay ` option is not mentioned in docs - I'll add it and make the value smaller, suppose it's safe to make it sth like 10 secs by default instead of 25 secs used currently.

Think I can also extend [infra tuning](https://centrifugal.dev/docs/server/infra_tuning) chapter with advices about possible network/infrastructure level protection techniques. The basic thing could be using Nginx [limit_conn_zone](https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html#limit_conn_zone) directive, [stick-table](https://www.haproxy.com/blog/introduction-to-haproxy-stick-tables/) in Haproxy, also Cloudflare provides rate limiting rules.

**Comment by FZambia** [comment]
* Added `client_stale_close_delay` to [docs](https://centrifugal.dev/docs/server/configuration#client_stale_close_delay), it's 10 secs in v4.1.3
* Added [Additional server protection](https://centrifugal.dev/docs/server/infra_tuning#additional-server-protection) section. Anyone can suggest extensions to that section now with advices based on real experience.

Closing, all addressed I suppose.
