### ISSUE TITLE
[question] v3 doc mention Redis must use In-memory or AOF+fsync but v4 don't - is it still actual?

### ISSUE THREAD

**Issue by powerman** [centrifugal/centrifugo#664]
https://centrifugal.dev/docs/3/server/history_and_recovery#automatic-message-recovery says:

> This also applies to the Redis engine – if you do not use AOF with fsync then sequences can be lost after Redis restart. When using the Redis engine you need to use a fully in-memory model strategy or AOF with fsync to guarantee the reliability of the recovered flag sent by Centrifugo.

Is it okay to use AOF with `appendfsync everysec` or it's required to use `appendfsync always`?

Why v4 doc https://centrifugal.dev/docs/server/history_and_recovery#automatic-message-recovery doesn't mention this anymore? Is it still actual for v4?

**Comment by FZambia** [comment]
Hello @powerman!

Centrifugo will properly tolerate message loss caused by broker problem when using message recovery feature in two scenarios:

* Everything was lost (so we can see that `epoch` changed and set proper `recovered` flag). In memory engine or single Redis node without AOF and RDB should provide this.
* Nothing is lost - single Redis node with AOF and `appendfsync always` should provide this.

Talking about master/replica Redis setup. Given the fact the replication in Redis is asynchronous there is a chance that upon master crash some messages won't reach the replica Redis node and will be missing when replica becomes master.

The fact that recovery may be broken when partial data loss happens in broker comes from the following thoughts:

* client has some offset and epoch
* master node changed (or Redis restarted and changes since last RDB snapshot missed)
* some messages could be sent but missing
* client resubscribes - missed messages are not available and we do not have a way to know about them at all, but epoch and offset are there - so there is a chance they will match those kept on client side.

In practice though all these considerations are not critical for most of Centrifugo use cases I believe. Centrifugo is not designed to be a primary message storage – the source of truth is application main database. So it may result into some UX inconvenience in the app (very rare!), which usually may be fixed by the app reload.

Our experimental Tarantool engine provides different guarantees out-of-the-box since it is persistent by default, also has synchronous replication option. But Redis is much simpler, more convenient to almost everyone.

**Comment by powerman** [comment]
Thanks!
