### ISSUE TITLE
[feature] Hierarchy based on namespace

### ISSUE THREAD

**Issue by vkitor** [centrifugal/centrifugo#670]
Hello,
Is there a way to send Messages to multiple channels at once based on namespace hierarchy?

For example, let's say I have 3 users (User1, User2 and User3) and they are subscribed to same namespace channel, but different "sub-channel":
- User1 -> chat:public
- User2 -> chat:hidden:admins
- User3 -> chat:hidden:moderators

Now if I send message to channel chat:public, only User1 will receive the message. But if I want to send message to all users, I would send it to channel chat. Or if i send message to channel chat:hidden, both User2 and User3 will receive the message.

**Comment by FZambia** [comment]
Hello,

I doubt it's possible because in this case we need to know the exact list of channels somehow. But there is no way to find this out.

Centrifugo provides [broadcast](https://centrifugal.dev/docs/server/server_api#broadcast) server API to publish data to many channels in one request. Probably it's not what you exactly need – but we definitely should know exact channels when publishing.
