### ISSUE TITLE
Details about unexpected client disconnects

### ISSUE THREAD

**Issue by sajjad-fatehi** [centrifugal/centrifugo#679]
hi :)
I had a question : 
How can I have number of unexpected client disconnects in the Grafana dashboard?
I also need the reason for the disconnect via the API as well as in the log. Is that possible?

thank you

**Comment by FZambia** [comment]
Hello,

> How can I have number of unexpected client disconnects in the Grafana dashboard?

The metric is called `centrifugo_client_num_server_disconnects`, I think it's already displayed in https://grafana.com/grafana/dashboards/13039-centrifugo/

> I also need the reason for the disconnect via the API as well as in the log. Is that possible?

I do not understand the question, can you clarify?

**Comment by mkhahani** [comment]
This is my question too.
Does `centrifugo_client_num_server_disconnects` metric represents all types of disconnect including user leave or just unexpected ones (that I need)?

**Comment by mkhahani** [comment]
Regarding the second question, I think Sajjad needs a way to distinguish between these two:
- normal disconnect (e.g. user leave)
- unexpected disconnect (e.g. network connectivity issue)

**Comment by sajjad-fatehi** [comment]
i mean how can i understand user disconnect reason (is unwanted disconnect or not) in `disconnectContext` or /disconnect rpc?

**Comment by FZambia** [comment]
> Does centrifugo_client_num_server_disconnects metric represents all types of disconnect including user leave or just unexpected ones (that I need)?

Not all types, see https://github.com/centrifugal/centrifuge/blob/e2cd8168c46d10a96fb04e8c7871963eb3c13d9e/client.go#L1029 - the metric only has disconnect codes which are not caused by normal client transport close. Actually it's common to see `no pong` code in metrics - this may indicate network close on client side, or busy rendering on app's side which resulted into disconnection.

> normal disconnect (e.g. user leave)
unexpected disconnect (e.g. network connectivity issue)

As mentioned above unexpected disconnect scenarios may be in metrics with `3012` (`no pong`) code. But depending on transport the connection may be closed when network is gone - we do not distinguish such cases, and it's mostly impossible I believe.

> i mean how can i understand user disconnect reason (is unwanted disconnect or not) in disconnectContext when an namespace join_leave is true ?

join_leave is about subscriptions, not connections. But trying to answer – join_leave event contexts do not contain any reason why subscription is gone.

**Comment by FZambia** [comment]
BTW, I just noticed that the [documentation about disconnect code numbers](https://centrifugal.dev/docs/server/codes) contained outdated information from Centrifugo v3 old client protocol where we did not have separation to terminal and non-terminal code numbers, I just updated it to be actual.

**Comment by sajjad-fatehi** [comment]
> BTW, I just noticed that Centrifugo [documentation about disconnect code numbers](https://centrifugal.dev/docs/server/codes) contained outdated information from Centrifugo v3 old client protocol where we did not have separation to terminal and non-terminal code numbers, I just updated it to be actual.

thank you :)

**Comment by FZambia** [comment]
I suppose can be closed, thanks for raising this - highlighted the problem with a doc.
