### ISSUE TITLE
[question] User-limited channels subscribe proxy

### ISSUE THREAD

**Issue by Larinel** [centrifugal/centrifugo#706]
Hi!

I was creating a simple application where the user connected to the centrifugo and a backend should generate some personalized data specifically for this user. The complication is that the backend should start generating data when the user connects to the centrifugo and end as soon as the user disconnects to save some resources.

The solution I was thinking of is to use user-limited channels(with granular proxy) with subscribe proxy and publish from the frontend once in a while(10 seconds or so) to let the backend know that the connection is not dead yet.

I ran into the issue when I couldn't send any initial data to the client because centrifugo does not send subscribe hook to the backend because I use user-limited channels. 

So either I have to disable user-limited channels and do an auth check on the backend or I can't send any initial data to the client. Either way seems a little bit odd, and I wanted to ask you what can you suggest in such a case.

P.S.
I would be happy to contribute some config flag that will enable a subscribe hook even for user-limited channels if you think it will fit.

**Comment by FZambia** [comment]
Hello @Larinel 

As for current behaviour - this was designed like this, and I suppose not using user-limited channels and making auth check on the backend side is pretty straightforward: Centrifugo provides channel and authenticated user ID in subscribe proxy request.

Though in general I  already thought that performing all checks on Centrifugo side and then issue subscribe proxy request for channels passed checks may be useful for some use cases. So some special mode for this may be good to have. I.e. some option which affects how Centrifugo checks permissions. I am not sure that it's a simple improvement and that it won't break some existing concepts. There are other permission related things like token-protected channels, etc - need to understand how this special option affects all of them. So some analytics required here.

I have a couple of questions about your use case if you don't mind:

1. Could you share what exactly you are doing and which resource should be cleaned up if user disconnects.
2. User can have many connections to Centrifugo - do you need content generation while user has at least one connection? Or you want to generate separate content for each individual user connection?
3. Probably instead of periodic pings from frontend you can periodically call Centrifugo Presence API. Hard to say whether it's a good idea or not without understanding details, but just pointing you to such possibility.
4. We have https://github.com/centrifugal/centrifugo/pull/680 - could you take a look, maybe it may be interesting for you. PR is a bit controversial and I am trying to evaluate whether it may help with such use cases.

**Comment by Larinel** [comment]
Hi @FZambia!
Thank you for the reply. 

Answers to the questions:
1. I meant computational resources. We do not want to generate data for a disconnected client.
2. We want to generate content for each individual connection, so a connect hook with occasional pings would be ideal for that.
3. We will look into it, thanks. Actually, I think we will open another question about that in a while because we had some issues with that as well, but we need a little bit more investigation ;)
4. The feature looks awesome, but I think it will consume a lot of resources in case you have hundreds of thousands of connections.

Anyway, thanks a lot, we will look into channel name validation on the backend side.

**Comment by FZambia** [comment]
Thanks for answers.

> We want to generate content for each individual connection, so a connect hook with occasional pings would be ideal for that.

You can make Centrifugo to send requests periodically by using refresh proxy

> The feature looks awesome, but I think it will consume a lot of resources in case you have hundreds of thousands of connections.

It will, and GRPC is quite tricky to scale. But the possibilities it opens look wonderful. Well, will continue collecting feedback :)

Regarding unsubscribe/disconnect hooks - I continue thinking about them, unfortunately guaranteed delivery of those hooks seems impossible to achieve as stated in our [FAQ](https://centrifugal.dev/docs/faq#why-centrifugo-does-not-have-disconnect-hooks), periodic jobs (pings/presence calls) are robust way to detect disconnections. Probably a compromise solution is fine here with a warning that disconnect hooks may only speed up disconnection detection but not reliable 100% of time.

**Comment by Larinel** [comment]
@FZambia as you mentioned refresh proxies. 

I was looking into them, but I ran into an issue that there is no way to call granular refresh proxy in case I am not using JWT auth. I want to use an auth handled by my backend, but I also want to be able to specify expiration for subscriptions.

Is there some architectural reason why there is no ability to specify connection expiration in the connection, but not in the subscription hook? Or I am simply missing something? As I see it, without JWT for a subscription, there is no way I can specify expiration for a subscription.

**Comment by FZambia** [comment]
> Is there some architectural reason why there is an ability to specify connection expiration in the connection hook, but not in the subscription hook? Or I am simply missing something?

Until this moment I was personally sure Centrifugo has it. There is a proxy protocol field which allows setting subscription expiration time similar to connect hook result: 

https://github.com/centrifugal/centrifugo/blob/d90e5c47e923b4724c46b76f400b3a29aea7795b/internal/proxyproto/proxy.proto#L131

But.. Seems that Centrifugo proxy implementation currently ignores the field. Will try to support it in nearest releases - it should be symmetrical to connection.

There is small thing about subscription expirations BTW - the timer which executes subscription refresh checks is not dedicated and check may be delayed up to 40 secs from the actual subscription expiration time. Which may be sufficient, bit not for every use case - sth to improve in the future - for now it was implemented this way to avoid using a dedicated timer.
