### ISSUE TITLE
[question] What are the ways of decreasing the message payload?

### ISSUE THREAD

**Issue by mcagridurgut** [centrifugal/centrifugo#775]
Hi, I am trying to establish a way to track the health / connection status of connections/subscriptions.  Also I need a way to show round trip time of websocket connection to each of my clients. For that I tried to come up with a custom ping/pong solution as mentioned in the [docs](https://centrifugal.dev/docs/faq#is-it-possible-to-listen-to-joinleave-events-on-the-app-backend-side) 

>  So the workaround here can be similar to one for disconnect – ping an app backend periodically while client is subscribed and thus know that client is currently in a channel with some approximation in time.

But the problem is that I am using publish function of the client sdk and there is a huge payload I sent with every ping message ( i.e. channel name, user data etc.) 

For example docs is telling me that I sent this type of payload for every rpc request

```
{
  "client":"9336a229-2400-4ebc-8c50-0a643d22e8a0",
  "transport":"websocket",
  "protocol": "json",
  "encoding":"json",
  "user":"56",
  "method": "getCurrentPrice",
  "data":{"params": {"object_id": 12}}
}
```

So I am wondering how can I decrease the payload to only include the fields I want? Since I will use ping/pong very frequently I do not want to spend much network resources. Also I know that centrifugo has an internal ping pong mechanism with 2 bytes, how can I send a similar low byte message?

**Comment by FZambia** [comment]
Hello, using GRPC may help to reduce size here, as field names won't be passed as strings. Generally speaking current structure does not seem a huge overhead for most cases especially since transfer will happen within your backend network. Also, maybe you can benefit from gzip compression here - https://centrifugal.dev/docs/server/proxy#proxy_grpc_compression.

There is no possibility to choose only fields you need at this point. Possible to add but I'd like to prove there is a real-life benefit from such a thing before optimizing this way.

Also, don't forget Centrifugo supports Protobuf protocol in client to server communication – it may help to reduce size of messages coming from client to server and from server to client.
