### ISSUE TITLE
Unable To Connect With anonymous mode

### ISSUE THREAD

**Issue by alouani-youssef** [centrifugal/centrifugo#782]
When I try to connect to the Centrifugo server using webSocket client 
 
 I got the following Error :
 `{"level":"info","client":"a4c0189c-ba87-4a0f-91c8-3e3631a87671","command":"id:151","reason":"bad request","user":"","time":"2024-03-06T16:51:22Z","message":"disconnect after handling command"}`.
 The Configuration file for the centrifugo server is:
 ``` 
 {
  "admin": false,
  "namespaces": [
    {
      "name": "interaction",
      "presence": true,
      "join_leave": true
    },
    {
      "name": "notifications"
    },
    {
      "name": "event"
    }
  ],
  "allowed_origins": [
    "*"
  ],
  "allow_subscribe_for_client": true,
  "allow_anonymous_connect_without_token": true
}
 ```
 within postman, the client I use to try to connect I got:
 3502 Error: stale

**Comment by FZambia** [comment]
Hello @alouani-youssef ,

Centrifugo has its own protocol, are you using our bidirectional SDK to connect? If yes - please share the code and also full server logs (I suggest enabling `"log_level": "trace"`) - not only last log message.

**Comment by FZambia** [comment]
You are sending wrong JSON commands, that's why connection is closed. You need to use [our SDKs](https://centrifugal.dev/docs/transports/client_sdk) to communicate with Centrifugo or use proper command structure (described [here](https://centrifugal.dev/docs/transports/client_protocol)). See also docs on [how to use Postman](https://centrifugal.dev/docs/transports/websocket#debugging-with-postman-wscat-etc) when you want to debug sth.

**Comment by FZambia** [comment]
Closing, hope it helped. Join our [community](https://centrifugal.dev/docs/getting-started/community) channels if you have any questions
