### ISSUE TITLE
[question] Upgrading to 4.1.5 increase in response time

### ISSUE THREAD

**Issue by dmeremyanin** [centrifugal/centrifugo#788]
### Synopsis

We are recently upgraded Centrifugo from v3.2.3 to v4.1.5 and after the upgrade we can see a significant increase in the response time of the `subscribe` command:

<img width="1439" alt="Screenshot 2024-03-19 at 10 53 08 PM" src="https://github.com/centrifugal/centrifugo/assets/241633/4de9847f-fc0c-450d-bbe6-75930ef31ee9">

<img width="1442" alt="Screenshot 2024-03-19 at 11 14 34 PM" src="https://github.com/centrifugal/centrifugo/assets/241633/38beb91e-c908-4ad0-8c43-4bc0e4dd9245">

### Question

Just wondering, is this the expected behavior?

**Comment by FZambia** [comment]
Hello @dmeremyanin,

Hard to say for sure - this may be related to Go version changes, or changes introduced in Centrifugo in the gap between versions v3.2.3 and v4.1.5, possible changes in configuration or environment upon migration.

Given you observe millisecond response times in `subscribe` I can assume the it's related to Redis or some network communication involved into resulting latency. One notable change I remember is switch to another Redis library in v4, but I am not sure whether it may be relevant since you have not provided enough details.

If you only observe increase in subscribe - but other commands are OK, then I am even more confident it's network/Redis/subscribe proxy related. But lacking details also.

**Comment by dmeremyanin** [comment]
Sorry for the poor details - we have 2 pods running Centrifugo and 3 pods running Redis Sentinel. The configuration wasn't changed at the update.

This is not a real issue, so feel free to close it. Thanks for the quick reply and the explanation 👍

**Comment by FZambia** [comment]
OK, you can reach out in the community groups and I can try to help looking at everything else to suggest sth. In general, sth like this may happen just because your new pods are running on another nodes of k8s. If you have time to experiment – I'd advice to try out other versions in between.
