### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by johndoejdg** [centrifugal/centrifugo#93]
In my application very need to know when someone disconnect from channel. So, will be good to have something like disconnect event from centrifugo server.

**Comment by johndoejdg** [comment]
I know about presence method. But it not good often send request on server. Please consider include system event when someone connect and disconnect in channel

**Comment by johndoejdg** [comment]
Answer found. Found that it possible by any official centrifugo client. But anyway, maybe you can consider include events functionality in server?

**Comment by FZambia** [comment]
Hello @johndoejdg ! I think that the way you found is the correct one. The core Centrifugo concept is to keep it as separate from application as possible - now Centrifugo knows nothing about application backend. In case of webhooks Centrifugo should at least know URL to POST events to application, should deal with timeouts somehow etc – these all results in more difficult and unpredictable Centrifugo behaviour which I prefer to keep as simple as possible. At moment it's pretty simple to send such events from client side yourself – moreover you get request already authenticated by your application session mechanism so know extra need in extra security checks.

Btw consider such situation – you have 50k users online and then something bad happens in datacenter and all clients get disconnected for a while from Centrifugo and then reconnect to it. It will be about 100k POST requests from Centrifugo to app backend in just a couple of seconds - I think for most applications it's a real disaster! Though this is also relevant for sending events from client side (but on client side you actually have more control when to send such events to server and when not - because you know if that disconnect action caused by your client).

**Comment by johndoejdg** [comment]
Ok, thank you for clarification.
